/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @author FusionCharts Technologies LLP
 @version fusioncharts/3.2.3-sr3.5322
*/
(function(){function ta(a){a=(a||0)%ua;return a<0?ua+a:a}function ya(a,c,d,b,g,j,e,f,k,m){if(typeof a==="object")c=a.y,d=a.r,b=a.innerR,g=a.radiusYFactor,j=a.depth,e=a.seriesGroup,f=a.renderer,a=a.x;if(g<0||g>=1)g=0.6;a=a||0;c=c||0;d=d||1;b=b||0;j=j||0;this.renderer=f;this.hasOnePoint=k;this.use3DLighting=m;this.cx=a;this.cy=c;this.rx=d;this.ry=d*g;this.radiusYFactor=g;this.isDoughnut=b>0;this.innerRx=b;this.innerRy=b*g;this.depth=j;this.leftX=a-d;this.rightX=a+d;this.leftInnerX=a-b;this.rightInnerX=
a+b;this.depthY=c+j;this.topY=c-this.ry;this.bottomY=this.depthY+this.ry;this.bottomBorderGroup=f.g("bottom-border").add(e).translate(0,j);this.outerBackGroup=f.g("outer-back-Side").add(e);this.slicingWallsBackGroup=f.g("slicingWalls-back-Side").add(e);this.innerBackGroup=f.g("inner-back-Side").add(e);this.innerFrontGroup=f.g("inner-front-Side").add(e);this.slicingWallsFrontGroup=f.g("slicingWalls-front-Side").add(e);this.outerFrontGroup=f.g("outer-front-Side").add(e);this.topGroup=f.g("top-Side").add(e);
this.moveCmdArr=[I];this.lineCmdArr=[O];this.closeCmdArr=[N];this.centerPoint=[a,c];this.leftPoint=[this.leftX,c];this.topPoint=[a,this.topY];this.rightPoint=[this.rightX,c];this.bottomPoint=[a,c+this.ry];this.leftDepthPoint=[this.leftX,this.depthY];this.rightDepthPoint=[this.rightX,this.depthY];this.leftInnerPoint=[this.leftInnerX,c];this.rightInnerPoint=[this.rightInnerX,c];this.leftInnerDepthPoint=[this.leftInnerX,this.depthY];this.rightInnerDepthPoint=[this.rightInnerX,this.depthY];this.pointElemStore=
[];this.slicingWallsArr=[];a=[da,this.rx,this.ry,0,0,1,this.rightX,c];d=[da,this.rx,this.ry,0,0,1,this.leftX,c];b=[da,this.rx,this.ry,0,0,0,this.rightX,this.depthY];g=[da,this.rx,this.ry,0,0,0,this.leftX,this.depthY];j=[da,this.innerRx,this.innerRy,0,0,0,this.rightInnerX,c];c=[da,this.innerRx,this.innerRy,0,0,0,this.leftInnerX,c];e=[da,this.innerRx,this.innerRy,0,0,1,this.rightInnerX,this.depthY];f=[da,this.innerRx,this.innerRy,0,0,1,this.leftInnerX,this.depthY];this.isDoughnut?(this.topBorderPath=
this.moveCmdArr.concat(this.leftPoint,a,d,this.moveCmdArr,this.leftInnerPoint,j,c),this.topPath=this.moveCmdArr.concat(this.leftPoint,a,d,this.lineCmdArr,this.leftInnerPoint,j,c,this.closeCmdArr),this.innerFrontPath=this.moveCmdArr.concat(this.leftInnerPoint,j,this.lineCmdArr,this.rightInnerDepthPoint,f,this.closeCmdArr),this.innerBackPath=this.moveCmdArr.concat(this.rightInnerPoint,c,this.lineCmdArr,this.leftInnerDepthPoint,e,this.closeCmdArr)):this.topBorderPath=this.topPath=this.moveCmdArr.concat(this.leftPoint,
a,d,this.closeCmdArr);this.outerBackPath=this.moveCmdArr.concat(this.leftPoint,a,this.lineCmdArr,this.rightDepthPoint,g,this.closeCmdArr);this.outerFrontPath=this.moveCmdArr.concat(this.rightPoint,d,this.lineCmdArr,this.leftDepthPoint,b,this.closeCmdArr);this.clipPathforOuter=[I,this.leftX,this.topY,O,this.rightX,this.topY,this.rightX,this.bottomY,this.leftX,this.bottomY,N];this.clipPathforInner=[I,this.leftInnerX,this.topY,O,this.rightInnerX,this.topY,this.rightInnerX,this.bottomY,this.leftInnerX,
this.bottomY,N];this.clipPathforNoClip=[I,this.leftInnerX,this.topY,O,this.leftInnerX,this.bottomY,N]}var na=FusionCharts(["private","modules.renderer.highcharts-charts"]);if(na!==void 0){var s=na.hcLib,L=s.BLANKSTRING,Ea=s.createTrendLine,r=s.pluck,S=s.getValidValue,n=s.pluckNumber,Y=s.defaultPaletteOptions,pa=s.getFirstValue,Za=s.getDefinedColor,ja=s.parseUnsafeString,T=s.FC_CONFIG_STRING,Fa=s.extend2,qa=s.getDashStyle,$a=s.toPrecision,ab=s.stubFN,P=s.Highcharts,bb=P.Series,Z=P.hasSVG,Ra=P.hasTouch,
ma=P.isIE,cb=P.extend,Sa=P.merge,za=P.pick,ha=P.each,Aa=P.attr,Ga=P.map,na=P.seriesTypes,va=P.addEvent,db=P.getPosition,Ba=P.getOptions().plotOptions,ra=function(a){return a!==Ha&&a!==null},Ha,eb="rgba(192,192,192,"+(Z?1.0E-6:0.0020)+")",oa=ma&&!Z?"visible":"",I="M",O="L",da="A",N="Z",fa=Math,X=fa.sin,$=fa.cos,fb=fa.atan2,Ca=fa.round,Ia=fa.min,ka=fa.max,Ta=fa.abs,Ja=fa.PI,Ia=fa.min,V=Ja/180,ba=Math.PI,Ka=ba/2,ua=2*ba,Ua=ba+Ka,gb=s.graphics.getColumnColor,M=s.getFirstColor,La=s.setLineHeight,Va=s.pluckFontSize,
wa=s.getFirstAlpha,sa=s.graphics.getDarkColor,la=s.graphics.getLightColor,ca=s.graphics.convertColor,Ma=s.COLOR_TRANSPARENT,Na=s.POSITION_CENTER,hb=s.POSITION_TOP,Da=s.POSITION_BOTTOM,ib=s.POSITION_RIGHT,jb=s.POSITION_LEFT,l=s.chartAPI,kb=s.titleSpaceManager,lb=s.placeLegendBlockBottom,mb=s.placeLegendBlockRight,Wa=s.graphics.mapSymbolName,Xa=l.singleseries,z=s.COMMASTRING,Ya=s.STRINGUNDEFINED,ga=s.ZEROSTRING,xa=s.ONESTRING,ea=s.HUNDREDSTRING,Oa=s.PXSTRING,nb=s.COMMASPACE;l("column2d",{standaloneInit:!0,
creditLabel:!0},l.column2dbase);l("column3d",{defaultSeriesType:"column3d",defaultPlotShadow:1},l.column2d);l("bar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:l.barbase},l.column2d);l("line",{standaloneInit:!0,creditLabel:!0},l.linebase);l("area2d",{standaloneInit:!0,creditLabel:!0},l.area2dbase);l("pie2d",{standaloneInit:!0,defaultSeriesType:"pie",defaultPlotShadow:1,point:function(a,c,d,b,g){var j,e,f,k=g[T],m=k.is3d,i,h,B,q,w=0,D=0,o=[],v=n(b.plotborderthickness,m?0.1:1),p=(f=n(b.use3dlighting,
1))?n(b.radius3d,b["3dradius"],90):100;i=n(b.showzeropies,1);var l=!0,F=n(b.showpercentintooltip,1),E=n(b.showlabels,1),u=n(b.showvalues,1),t=n(b.showpercentvalues,b.showpercentagevalues,0),G=r(b.tooltipsepchar,b.hovercapsepchar,nb),x=r(b.labelsepchar,G),J=r(b.plotbordercolor,b.piebordercolor),s=g[T].numberFormatter;h=d.length;var K,y,I=n(b.plotborderdashed,0),H=n(b.plotborderdashlen,5),C=n(b.plotborderdashgap,4);p>100&&(p=100);p<0&&(p=0);if(n(b.showlegend,0))g.legend.enabled=!0,g.legend.reversed=
!Boolean(n(b.reverselegend,0)),c.showInLegend=!0;if(!E&&!u)g.plotOptions.series.dataLabels.enabled=!1,g.tooltip.enabled===!1&&(l=!1);for(a=0;a<h;a+=1)e=d[a],j=s.getCleanValue(e.value,!0),j===null||!i&&j===0||(o.push(e),w+=j);w===0&&(o=[]);c.enableRotation=o.length>1?n(b.enablerotation,1):0;c.is3D=m;c.use3DLighting=f;c.pieYScale=n(b.pieyscale,40);if(c.pieYScale<1)c.pieYScale=1;c.pieYScale/=100;c.pieSliceDepth=n(b.pieslicedepth,15);if(c.pieSliceDepth<1)c.pieSliceDepth=1;c.managedPieSliceDepth=c.pieSliceDepth;
for(a=o.length-1;a>=0;a-=1){e=o[a];j=s.getCleanValue(e.value,!0);d=ja(r(e.label,e.name,L));i=r(e.color,g.colors[a%g.colors.length]);h=r(e.alpha,b.plotfillalpha,ea);B=r(e.bordercolor,J,la(i,m?90:25)).split(z)[0];q=b.showplotborder==ga?ga:r(e.borderalpha,b.plotborderalpha,b.pieborderalpha,"80");f={opacity:Math.max(h,q)/100};if(K=Boolean(n(e.issliced,b.issliced,0)))k.preSliced=K;y=n(e.dashed,I)?qa(r(e.dashlen,H),r(e.dashgap,C),v):void 0;c.data.push({showInLegend:d!==L,y:j,name:d,shadow:f,toolText:ja(S(e.tooltext)),
color:this.getPointColor(i,h,p),_3dAlpha:h,borderColor:ca(B,q),borderWidth:v,link:S(e.link),sliced:K,dashStyle:y,doNotSlice:r(b.enableslicing,xa)!=xa});if(l)i=s.percentValue(j/w*100),h=s.dataLabels(j)||L,f=F===1?i:h,j=E===1?d:L,i=u===1?t===1?i:h:L,i=(e=S(e.displayvalue))?e:i!==L&&j!==L?j+x+i:r(j,i),d=d!=L?d+G+f:f,e=c.data[D],e.displayValue=i,e.toolText=r(e.toolText,d),D+=1}g.legend.enabled=b.showlegend==xa?!0:!1;g.chart.startingAngle=r(b.startingangle,0);return c},getPointColor:function(a,c,d){var b,
g,a=M(a),c=wa(c);d<100&&Z?(b=Math.floor((100-0.35*d)*85)/100,b=sa(a,b),g=Math.floor((100+d)*50)/100,a=la(a,g),c={FCcolor:{color:a+z+b,alpha:c+z+c,ratio:d+",100",radialGradient:!0}}):c={FCcolor:{color:a+z+a,alpha:c+z+c,ratio:"0,100"}};return c},configureAxis:function(a){var c=0,d=a[T],b;a.plotOptions.series.dataLabels.style=a.xAxis.labels.style;a.plotOptions.series.dataLabels.color=a.xAxis.labels.style.color;delete d.x;delete d[0];delete d[1];a.chart.plotBorderColor=a.chart.plotBackgroundColor=Ma;
d=d.pieDATALabels=[];if(a.series.length===1&&(b=a.series[0].data)&&(c=a.series[0].data.length)>0&&a.plotOptions.series.dataLabels.enabled)for(;c--;)b[c]&&S(b[c].displayValue)!==void 0&&d.push(b[c].displayValue)},spaceManager:function(a,c,d,b){var g=a[T],j=g.is3d,e=this.name,f=g.smartLabel,k=n(g.pieDATALabels&&g.pieDATALabels.length,0),m=0,i=c.chart,h=n(i.managelabeloverflow,0),B=!g.preSliced&&i.enableslicing==ga&&(i.showlegend!=xa||i.interactivelegend==ga)?0:n(i.slicingdistance,20),q=n(i.pieradius,
0),w=n(i.enablesmartlabels,i.enablesmartlabel,1),D=w?n(i.skipoverlaplabels,i.skipoverlaplabel,1):0,o=n(i.issmartlineslanted,1),v=n(i.labeldistance,i.nametbdistance,5),p=n(i.smartlabelclearance,5);d-=a.chart.marginRight+a.chart.marginLeft;var l=b-(a.chart.marginTop+a.chart.marginBottom),b=Math.min(l,d),F=r(i.smartlinecolor,Y.plotFillColor[a.chart.paletteIndex]),E=n(i.smartlinealpha,100),u=n(i.smartlinethickness,1),t=a.plotOptions.series.dataLabels,G=t.style,x=n(parseInt(G.lineHeight,10),12),J=a.series[0],
s=J.pieYScale,K=J.pieSliceDepth,b=q===0?b*0.15:q,y=0,y=2*b;t.connectorWidth=u;t.connectorColor=ca(F,E);l-=kb(a,c,d,y<l?l-y:l/2);i.showlegend==xa&&(r(i.legendposition,Da).toLowerCase()!=ib?l-=lb(a,c,d,l/2,!0):d-=mb(a,c,d/3,l,!0));f.setStyle(G);if(k!==1)for(;k--;)c=f.getOriSize(g.pieDATALabels[k]),m=Math.max(m,c.width);w&&(v=p+B);q===0&&(j?(l-=K,y=Math.min(d/2-m,(l/2-x)/s)-v):y=Math.min(d/2-m,l/2-x)-v,y>=b?b=y:v=Math.max(v-(b-y),B));if(j&&(k=l-2*(b*s+x),K>k))J.managedPieSliceDepth=K-k;a.plotOptions.pie3d.slicedOffset=
a.plotOptions.pie.slicedOffset=B;a.plotOptions.pie3d.size=a.plotOptions.pie.size=2*b;a.plotOptions.series.dataLabels.distance=v;a.plotOptions.series.dataLabels.isSmartLineSlanted=o;a.plotOptions.series.dataLabels.enableSmartLabels=w;a.plotOptions.series.dataLabels.skipOverlapLabels=D;a.plotOptions.series.dataLabels.manageLabelOverflow=h;if(e==="doughnut2d"||e==="doughnut3d")if(e=n(i.doughnutradius,0),k=n(i.use3dlighting,1)?n(i.radius3d,i["3dradius"],50):100,k>100&&(k=100),k<0&&(k=0),i=e===0||e>=b?
b/2:e,a.plotOptions.pie3d.innerSize=a.plotOptions.pie.innerSize=2*i,k>0&&Z&&(i=parseInt(i/b*100,10),e=(100-i)/2,k=parseInt(e*k/100,10),i=i+z+k+z+2*(e-k)+z+k,a.series[0]&&a.series[0].data)){h=a.series[0].data;a=0;for(k=h.length;a<k;a+=1)if(e=h[a],e.color.FCcolor)e.color.FCcolor.ratio=i}},creditLabel:!0,eiMethods:{togglePieSlice:function(a){var c=this.jsVars.hcObj,d;if(c&&c.series&&(d=c.series[0])&&d.data&&d.data[a]&&d.data[a].slice)return d.data[d.xIncrement-1-a].slice()}}},Xa);l("pie3d",{defaultSeriesType:"pie3d",
creditLabel:!0,getPointColor:function(a){return a},defaultPlotShadow:0},l.pie2d);l("doughnut2d",{getPointColor:function(a,c,d){var b,a=M(a),c=wa(c);d<100&&Z?(b=Math.floor((85-0.2*(100-d))*100)/100,b=sa(a,b),d=Math.floor((100-0.5*d)*100)/100,a=la(a,d),c={FCcolor:{color:b+z+a+z+a+z+b,alpha:c+z+c+z+c+z+c,radialGradient:!0}}):c={FCcolor:{color:a+z+a,alpha:c+z+c,ratio:"0,100"}};return c}},l.pie2d);l("doughnut3d",{defaultSeriesType:"pie3d",getPointColor:l.pie3d,defaultPlotShadow:0},l.doughnut2d);l("pareto2d",
{standaloneInit:!0,point:function(a,c,d,b,g){var j,e,f,k,m,i,h,B,q,w,D,o,v,p,l,a=d.length,F=0;i={};v=g.chart.paletteIndex;var E=/3d$/.test(g.chart.defaultSeriesType),u=this.isBar,t=r(360-b.plotfillangle,90),G=n(b.plotborderthickness,1),x=g.chart.useRoundEdges,J=r(b.tooltipsepchar,", "),s=r(b.plotbordercolor,Y.plotBorderColor[v]).split(z)[0],K=b.showplotborder==ga?ga:r(b.plotborderalpha,b.plotfillalpha,ea),y=g.xAxis,I=n(b.showcumulativeline,1),H=g[T],C=H.axisGridManager,O=H.x,N=b.showtooltip!=ga,A=
[],Q=[],aa=n(b.use3dlighting,1),R=g[T].numberFormatter,P=n(b.showlinevalues,b.showvalues),U=n(b.plotborderdashed,0),X=n(b.plotborderdashlen,5),$=n(b.plotborderdashgap,4),K=E?b.showplotborder?K:ga:K,s=E?r(b.plotbordercolor,"#FFFFFF"):s;for(o=e=0;e<a;e+=1)if(D=d[e],d[e].vline)C.addVline(y,D,o,g);else if(j=R.getCleanValue(D.value,!0),j!==null)D.value=j,A.push(D),o+=1;a=A.length;A.sort(function(a,b){return b.value-a.value});if(I)h=n(b.linedashed,0),p=M(r(b.linecolor,Y.plotBorderColor[v])),e=r(b.linealpha,
100),B=n(b.linedashlen,5),q=n(b.linedashgap,4),i=n(b.linethickness,2),w={opacity:e/100},l=n(b.drawanchors,b.showanchors),l===void 0&&(l=e!=ga),f=n(b.anchorborderthickness,1),m=n(b.anchorsides,0),k=n(b.anchorradius,3),o=M(r(b.anchorbordercolor,p)),j=M(r(b.anchorbgcolor,Y.anchorBgColor[v])),d=wa(r(b.anchoralpha,ea)),D=wa(r(b.anchorbgalpha,d))*d/100,h=h?qa(B,q,i):void 0,i={yAxis:1,data:[],type:"line",color:ca(p,e),lineWidth:i,marker:{enabled:l,fillColor:ca(j,D),lineColor:ca(o,d),lineWidth:f,radius:k,
symbol:Wa(m),startAngle:r(b.anchorstartangle,90)}};else{if(b.showsecondarylimits!=="1")b.showsecondarylimits="0";if(b.showdivlinesecondaryvalue!=="1")b.showdivlinesecondaryvalue="0"}for(e=0;e<a;e+=1)D=A[e],j=n(D.showlabel,b.showlabels,1),d=ja(!j?L:pa(D.label,D.name)),C.addXaxisCat(y,e,e,d),F+=j=D.value,f=r(D.color,g.colors[e%g.colors.length])+z+Za(b.plotgradientcolor,Y.plotGradientColor[v]),k=r(D.alpha,b.plotfillalpha,ea),m=r(D.ratio,b.plotfillratio),o={opacity:k/100},p=r(D.alpha,K)+L,f=gb(f,k,m,
t,x,s,p,u,E),c.data.push(Fa(this.getPointStub(D,j,d,g),{y:j,shadow:o,color:f[0],borderColor:f[1],borderWidth:G,use3DLighting:aa,dashStyle:n(D.dashed,U)==1?qa(X,$,G):""})),this.pointValueWatcher(g,j),I&&Q.push({value:F,dataLabel:d,tooltext:S(D.tooltext)});O.catCount=a;H[1]||(H[1]={});H[1].stacking100Percent=!0;if(I&&F>0){e=0;for(a=Q.length;e<a;e+=1)D=Q[e],g=c.data[e],j=D.value/F*100,v=R.percentValue(j),b=g.displayValue!==L?v:L,P==1&&(b=v),P==0&&(b=L),d=D.dataLabel,v=N?D.tooltext!==void 0?D.tooltext:
(d!==L?d+J:L)+v:L,i.data.push({shadow:w,y:j,toolText:v,displayValue:b,link:g.link,dashStyle:h});return[c,i]}else return c},defaultSeriesType:"column",isDual:!0,creditLabel:!0},Xa);l("pareto3d",{defaultSeriesType:"column3d",defaultPlotShadow:1},l.pareto2d);l("mscolumn2d",{standaloneInit:!0,creditLabel:!0},l.mscolumn2dbase);l("mscolumn3d",{defaultSeriesType:"column3d",defaultPlotShadow:1},l.mscolumn2d);l("msbar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:l.barbase},l.mscolumn2d);l("msbar3d",{defaultSeriesType:"bar3d",
defaultPlotShadow:1},l.msbar2d);l("msline",{standaloneInit:!0,creditLabel:!0},l.mslinebase);l("msarea",{standaloneInit:!0,creditLabel:!0},l.msareabase);l("stackedcolumn2d",{isStacked:!0},l.mscolumn2d);l("stackedcolumn3d",{isStacked:!0},l.mscolumn3d);l("stackedbar2d",{isStacked:!0},l.msbar2d);l("stackedbar3d",{isStacked:!0},l.msbar3d);l("stackedarea2d",{isStacked:!0,showSum:0},l.msarea);l("marimekko",{isValueAbs:!0,distributedColumns:!0,isStacked:!0,xAxisMinMaxSetter:ab,postSeriesAddition:function(a,
c){var d=a[T],b,g,j,e,f,k=0;e=a.xAxis;var m,i=100/d.marimekkoTotal,h=[],B=a.series,q,w=0,D,o=n(c.chart.plotborderthickness,1),l=a.chart.rotateValues,p=n(c.chart.rotatexaxispercentvalues,0),o=o*-0.5-(o%2+(p?0:4)),r=p?3:0,F=l?270:0;g=d[0];var E=!g.stacking100Percent,u=d.inCanvasStyle;d.isXYPlot=!0;d.distributedColumns=!0;e.min=0;e.max=100;e.labels.enabled=!1;e.gridLineWidth=0;e.alternateGridColor=Ma;b=g.stack;c.chart.interactivelegend="0";f=0;for(g=a.xAxis.plotLines.length;f<g;f+=1)if(m=e.plotLines[f],
m.isGrid)m.isCat=!0,h[m.value]=m;if(b.floatedcolumn&&(j=b.floatedcolumn[0])){b=0;for(g=j.length;b<g;){k+=e=j[b].p||0;q=e*i;m=w+q/2;D=w+q;for(f=0;f<B.length;f+=1)a.series[f].data[b]._FCX=w,a.series[f].data[b]._FCW=q;d.showStackTotal&&a.xAxis.plotLines.push({value:m,width:0,isVline:E,isTrend:!E,label:{align:Na,textAlign:F,rotation:l?270:0,style:d.trendStyle,verticalAlign:hb,y:0,x:0,text:this.numberFormatter.yAxis($a(e,10))}});if(h[b])h[b].value=m,h[b]._weight=q;b+=1;d.showXAxisPercentValues&&b<g&&a.xAxis.plotLines.push({value:D,
width:0,isVine:!0,label:{align:Na,textAlign:p?jb:Na,rotation:p?270:0,style:{color:u.color,fontSize:u.fontSize,fontFamily:u.fontFamily,lineHeight:u.lineHeight,border:"1px solid",borderColor:u.color,backgroundColor:"#ffffff",backgroundOpacity:1},verticalAlign:Da,y:o,x:r,text:this.numberFormatter.percentValue(D)},zIndex:5});w=D}}},defaultSeriesType:"floatedcolumn"},l.stackedcolumn2d);l("msstackedcolumn2d",{series:function(a,c,d){var b,g,j,e,f=c[T],k=0,m,i;m=[];var h;c.legend.enabled=Boolean(n(a.chart.showlegend,
1));if(a.dataset&&a.dataset.length>0){this.categoryAdder(a,c);b=0;for(g=a.dataset.length;b<g;b+=1)if(h=a.dataset[b].dataset){j=0;for(e=h.length;j<e;j+=1,k+=1)m={data:[],stack:b},i=Math.min(f.oriCatTmp.length,h[j].data&&h[j].data.length),m=this.point(d,m,h[j],a.chart,c,i,k,b),c.series.push(m)}if(this.isDual&&a.lineset&&a.lineset.length>0){j=0;for(e=a.lineset.length;j<e;j+=1,k+=1)m={data:[],yAxis:1,type:"line"},d=a.lineset[j],i=Math.min(f.oriCatTmp.length,d.data&&d.data.length),c.series.push(l.msline.point.call(this,
"msline",m,d,a.chart,c,i,k))}this.configureAxis(c,a);a.trendlines&&Ea(a.trendlines,c.yAxis,c[T],!1,this.isBar)}}},l.stackedcolumn2d);l("mscombi2d",{series:function(a,c,d){var b,g,j,e,f=a.chart,k,m=[],i=[],h=[],B,q,w=c[T],D=this.isDual;c.legend.enabled=Boolean(n(a.chart.showlegend,1));if(a.dataset&&a.dataset.length>0){this.categoryAdder(a,c);e=w.oriCatTmp.length;b=0;for(g=a.dataset.length;b<g;b+=1){j=a.dataset[b];B=D&&r(j.parentyaxis,"p").toLowerCase()==="s"?!0:!1;k={data:[]};if(B)k.yAxis=1;q=pa(j.renderas,
L).toLowerCase();switch(q){case "line":k.type="line";m.push(l.msline.point.call(this,d,k,j,f,c,e,b));break;case "area":k.type="area";c.chart.series2D3Dshift=!0;h.push(l.msarea.point.call(this,d,k,j,f,c,e,b));break;case "column":i.push(l.mscolumn2d.point.call(this,d,k,a.dataset[b],f,c,e,b));break;default:B?(k.type="line",m.push(l.msline.point.call(this,d,k,j,f,c,e,b))):i.push(l.mscolumn2d.point.call(this,d,k,a.dataset[b],f,c,e,b))}}c.series=f.areaovercolumns!=="0"?c.series.concat(i,h,m):c.series.concat(h,
i,m);if(i.length===0)w.hasNoColumn=!0;this.configureAxis(c,a);a.trendlines&&Ea(a.trendlines,c.yAxis,c[T],D,this.isBar)}}},l.mscolumn2d);l("mscombi3d",{series:l.mscombi2d.series,eiMethods:"view2D,view3D,resetView,rotateView,getViewAngles,fitToStage"},l.mscolumn3d);l("mscolumnline3d",{},l.mscombi3d);l("stackedcolumn2dline",{isStacked:!0,stack100percent:0},l.mscombi2d);l("stackedcolumn3dline",{isStacked:!0,stack100percent:0},l.mscombi3d);l("mscombidy2d",{isDual:!0},l.mscombi2d);l("mscolumn3dlinedy",
{isDual:!0},l.mscolumnline3d);l("stackedcolumn3dlinedy",{isDual:!0},l.stackedcolumn3dline);l("msstackedcolumn2dlinedy",{isDual:!0,stack100percent:0},l.msstackedcolumn2d);l("scrollcolumn2d",{postSeriesAddition:l.scrollbase.postSeriesAddition,avgScrollPointWidth:40},l.mscolumn2d);l("scrollline2d",{postSeriesAddition:l.scrollbase.postSeriesAddition,avgScrollPointWidth:75},l.msline);l("scrollarea2d",{postSeriesAddition:l.scrollbase.postSeriesAddition,avgScrollPointWidth:75},l.msarea);l("scrollstackedcolumn2d",
{postSeriesAddition:function(a,c,d,b){l.base.postSeriesAddition.call(this,a,c,d,b);l.scrollbase.postSeriesAddition.call(this,a,c,d,b)},avgScrollPointWidth:75},l.stackedcolumn2d);l("scrollcombi2d",{postSeriesAddition:l.scrollbase.postSeriesAddition,avgScrollPointWidth:40},l.mscombi2d);l("scrollcombidy2d",{postSeriesAddition:l.scrollbase.postSeriesAddition,avgScrollPointWidth:40},l.mscombidy2d);l("scatter",{standaloneInit:!0,defaultSeriesType:"scatter",creditLabel:!0},l.scatterbase);l("bubble",{standaloneInit:!0,
standaloneInut:!0,defaultSeriesType:"bubble",point:function(a,c,d,b,g,j,e){if(d.data){var f,k,m,i,h,B,q,w,D,o,v=!1,p,ia,a=l[a],j=d.data,F=j.length,E=n(d.showvalues,g[T].showValues);m=n(b.bubblescale,1);var u=r(b.negativecolor,"FF0000"),t=g.plotOptions.bubble,G=this.numberFormatter,x=n(d.showregressionline,b.showregressionline,0);t.bubbleScale=m;c.name=S(d.seriesname);if(n(d.includeinlegend)===0||c.name===void 0)c.showInLegend=!1;m=Boolean(n(d.drawanchors,d.showanchors,b.drawanchors,1));q=r(d.plotfillalpha,
d.bubblefillalpha,b.plotfillalpha,ea);w=n(d.showplotborder,b.showplotborder,1);D=M(r(d.plotbordercolor,b.plotbordercolor,"666666"));f=r(d.plotborderthickness,b.plotborderthickness,1);o=r(d.plotborderalpha,b.plotborderalpha,"95");w=w==1?f:0;e=r(d.color,d.plotfillcolor,b.plotfillcolor,g.colors[e%g.colors.length]);c.marker={enabled:m,fillColor:this.getPointColor(e,ea),lineColor:{FCcolor:{color:D,alpha:o}},lineWidth:w,symbol:"circle"};if(x){c.events={hide:this.hideRLine,show:this.showRLine};var J={sumX:0,
sumY:0,sumXY:0,sumXsqure:0,sumYsqure:0,xValues:[],yValues:[]},s=n(d.showyonx,b.showyonx,1),K=M(r(d.regressionlinecolor,b.regressionlinecolor,e)),y=n(d.regressionlinethickness,b.regressionlinethickness,1);f=wa(n(d.regressionlinealpha,b.regressionlinealpha,100));K=ca(K,f)}for(k=0;k<F;k+=1)if(i=j[k])if(f=G.getCleanValue(i.y),p=G.getCleanValue(i.x),ia=G.getCleanValue(i.z,!0),f===null)c.data.push({y:null,x:p});else{v=!0;h=M(r(i.color,i.z<0?u:e));B=r(i.alpha,q);i=a.getPointStub(i,f,p,g,d,E);h=n(b.use3dlighting)===
0?h:a.getPointColor(h,B);if(ia!==null)t.zMax=t.zMax>ia?t.zMax:ia,t.zMin=t.zMin<ia?t.zMin:ia;c.data.push({y:f,x:p,z:ia,displayValue:i.displayValue,toolText:i.toolText,link:i.link,marker:{enabled:m,fillColor:h,lineColor:{FCcolor:{color:D,alpha:o}},lineWidth:w,symbol:"circle"}});this.pointValueWatcher(g,f,p,x&&J)}else c.data.push({y:null});x&&(d={type:"line",color:K,showInLegend:!1,lineWidth:y,enableMouseTracking:!1,marker:{enabled:!1},data:this.getRegressionLineSeries(J,s,F),zIndex:0},c=[c,d])}if(!v)c.showInLegend=
!1;return c},postSeriesAddition:function(a,c){a.chart.hasScroll=n(c.chart.clipbubbles,1)},getPointStub:function(a,c,d,b,g,j){var b=b[T],c=c===null?c:b.numberFormatter.dataLabels(c),e,f=b.tooltipSepChar;b.showTooltip?S(a.tooltext)!==void 0?g=ja(a.tooltext):c===null?g=!1:(b.seriesNameInToolTip&&(e=r(g&&g.seriesname)),g=e?e+f:L,g+=d?d+f:L,g+=c,g+=a.z?f+a.z:L):g=L;d=n(a.showvalue,j,b.showValues)?r(a.name,a.label)!==void 0?ja(r(a.name,a.label)):c:L;a=S(a.link);return{displayValue:d,toolText:g,link:a}}},
l.scatter);var Pa=function(a,c,d,b){var t;var g=a.stepZoom,j=g.zoomHistory,e=g.currentZoomLevelIndex,f,k=g.pixelsPerPoint,m=a.series,i=m.length,h=g.maxIndex,B,q,w,D;q=a.options._FCconf.visibleLabelDistance;var o;if(b<e)e=g.currentZoomLevelIndex=b||0,j.splice(e+1,j.length),j=j[e],k=j.stepping,a=j.seriesStart,d=j.perPointPixelDistance,b=j.scrollRatio,c=g.scrollPosition=j.scrollPosition,g.scrollablePXLength=j.scrollablePXLength;else{c>d&&(o=c,c=d,d=o);f=a.plotWidth;a=d-c;d=f/a;o=d<q?Math.ceil(q/d):1;
k=d<k?Math.ceil(k/d):1;d=f/(a-a%k);a=c%k;B=h-h%k;w=(B-a)*d;b=f/w;D=w-f;c=D>0?(c-a)*d/(w-f):0;g.scrollPosition=c;g.scrollablePXLength=D;if((f=j[e])&&f.stepping===k&&f.seriesStart===a&&f.seriesEnd===B&&f.perPointPixelDistance===d)return;j[g.currentZoomLevelIndex=e+=1]={seriesStart:a,seriesEnd:B,stepping:k,perPointPixelDistance:d,visiblePointDistance:k*d,seriesConf:[],scrollRatio:b,scrollPosition:c,scrollablePXLength:D}}var j=[],n,p;o===void 0&&(o=d<q?Math.ceil(q/d):1);for(e=0;e<=h;e+=1){B=e-a;q=B*d;
D=q+g.xDisplacement;f=B<0||B%k!==0;B=(B=B<0||B%o!==0)?"hide":"show";if(w=g.catLabelArr[e])w[B](),w.attr({x:D});for(D=0;D<i;D+=1)if(n=m[D],w=n.data[e],w.plotX=q,t=j[D]||(j[D]={path:[],addMove:!0,addLine:!1,lastMovePoint:[],connectNullData:n.options.connectNullData}),n=t,p=n.path,w.graphic&&(w.graphic.attr({x:q}),w.graphic[B]()),w.dataLabel&&w.dataLabel.attr&&(w.dataLabel.attr({x:q}),w.dataLabel[B]()),w.tracker&&w.tracker.attr&&(w.tracker.attr({x:q}),w.tracker[B]()),!f)if(ra(w&&w.plotY)){if(n.addLine)p.push(I,
n.lastMovePoint[0],n.lastMovePoint[1],O),n.addLine=!1;n.addMove?(n.addLine=!0,n.addMove=!1,n.lastMovePoint[0]=q,n.lastMovePoint[1]=w.plotY):p.push(q,w.plotY)}else if(!n.connectNullData)n.addMove=!0,n.addLine=!1}for(D=0;D<i;D+=1)n=j[D]||(j[D]={path:[I],isLastMoveComand:!0}),p=n.path,m[D].graphLine.attr({d:p}),m[D].graphPath=p;g.scroller.setScrollRatio(b);g.scroller.setScrollPosition(c)},ob=function(a,c){var d=c.zoomHistory[c.currentZoomLevelIndex],b=d.perPointPixelDistance,g=a.selectionWidth,j=c.maxIndex,
d=d.scrollablePXLength*d.scrollPosition+a.selectionLeft,g=d+g,d=Math.floor(d/b),g=Math.ceil(g/b);g>j&&(g=j);return{max:g,min:d}},pb=function(a,c){var d=this.tracker.normalizeMouseEvent,b=this.options.chart.stepZoom,g=this.renderer,j=this.plotLeft,e=this.plotTop,f=this.plotWidth,k=this.plotHeight,m=b.pinPaneBorderThickness,i=g.clipRect(j+a,e,c,k),h,B,q=[],n=0;h=g.g("group").attr({x:0,y:0,zIndex:2}).clip(i).add();B=g.rect(j+a,e-m/2,c,k+m,0).attr({stroke:b.pinPaneBorderColor,fill:b.pinPaneBgColor,strokeWidth:m}).css({cursor:"w-resize"}).add(h);
ha(this.series,function(a){var d=a.options,c=d.color,d=ka(d.lineWidth+b.pinLineThicknessDelta,1),c=g.path(a.graphPath).attr({stroke:c,"stroke-width":d,"stroke-linecap":"round",dashstyle:ma&&!Z?qa(d+1,d,d):qa(d,d+1,d)});q.push(c);c.translate(a.group.attr("translateX"),e).add(h)});va(B.element,"dragstart drag",function(b){b=d(b);if(b.type==="dragstart")n=b.pageX-(h.attr("translateX")||0);else{var b=b.pageX-n,e=b+a;e<0?b=-a:e+c>f&&(b=f-c-a);h.translate(b)}});return{destroy:function(){ha(q,function(a){a.destroy()});
B.destroy();h.destroy()}}},qb=function(a){var c=this,d=c.stepZoom,b=c.options.chart.stepZoom,g=a.selectionLeft,j=ob(a,d);if(d.pinActive)d.pinComposite&&d.pinComposite.destroy(),d.pinComposite=pb.call(c,g,a.selectionWidth,j,d);else{j.max>j.min&&Pa(c,j.min,j.max);a=d.currentZoomLevelIndex;if(!d.zoButton)d.zoButton=c.addButton({onclick:function(){var a=d.currentZoomLevelIndex-1;Pa(c,void 0,void 0,a);d.pinComposite&&(d.pinComposite=d.pinComposite.destroy());d.pinButton&&d.pinButton.activate(!1);d.pinActive=
!1;a<=1&&d.resetButton.hide();d.currentZoomLevelIndex==0&&d.zoButton.hide()},tooltip:b.showToolBarButtonTooltext&&b.btnZoomOutTooltext,symbol:"zoomOutIcon"});d.zoButton[a===0?"hide":"show"]();if(!d.resetButton)d.resetButton=c.addButton({onclick:function(){Pa(c,void 0,void 0,0);d.resetButton&&d.resetButton.hide();d.zoButton&&d.zoButton.hide();d.pinComposite&&(d.pinComposite=d.pinComposite.destroy());d.pinButton&&d.pinButton.activate(!1);d.pinActive=!1},tooltip:b.showToolBarButtonTooltext&&b.btnResetChartTooltext,
symbol:"resetIcon",symbolFill:"none",hoverSymbolFill:"none"});d.resetButton[c.stepZoom.currentZoomLevelIndex>1?"show":"hide"]()}};l("zoomline",{standaloneInit:!0,hasVDivLine:!0,defaultSeriesType:"stepzoom",canvasborderthickness:1,chart:function(){var a=this.dataObj.chart,c=this.base.chart.apply(this,arguments),d=c.chart.stepZoom;!S(a.caption)&&!S(a.subcaption)&&(c.chart.marginTop+=15);c.chart.animation=!1;(c.plotOptions||(c.plotOptions={}))&&(c.plotOptions.series||(c.plotOptions.series={}));c.plotOptions.series.animation=
!1;c.chart.nativeZoom=!1;c.chart.events.selection=qb;if(!c.callbacks)c.callbacks=[];c.callbacks.push(function(){var a=this.stepZoom,c=a.pinButton;if(!c&&this.options.chart.stepZoom.allowPinMode)c=a.pinButton=this.addButton({onclick:function(){if(a.pinActive=!a.pinActive)c.tooltipOptions.point.toolText=d.showToolBarButtonTooltext&&"Switch to Zoom Mode";else{if(a.pinComposite)a.pinComposite=a.pinComposite.destroy();c.tooltipOptions.point.toolText=d.showToolBarButtonTooltext&&d.btnSwitchToPinModeTooltext}c.activate(a.pinActive)},
tooltip:d.showToolBarButtonTooltext&&d.btnSwitchToPinModeTooltext,symbol:"pinModeIcon"})});return c},xAxisMinMaxSetter:function(a){this.base.xAxisMinMaxSetter.apply(this,arguments);var c=a.xAxis,d=a[T].x;c.min=0;c.max=d.catCount-1},series:function(a,c,d){var b,g,j=c[T],e;b=a.chart;n(b.compactdatamode,0);c.legend.enabled=Boolean(n(b.showlegend,1));c.chart.valuePosition=r(b.valueposition,"auto").toLowerCase();if(a.dataset&&a.dataset.length>0){a.categories&&a.categories[0]&&a.categories[0].category&&
this.categoryAdder(a,c);b=0;for(g=a.dataset.length;b<g;b+=1)if(a.dataset[b].data)e={data:[]},e=this.point(d,e,a.dataset[b],a.chart,c,j.oriCatTmp.length,b),e instanceof Array?c.series=c.series.concat(e):c.series.push(e),e=!0;e&&(this.configureAxis(c,a),a.trendlines&&!this.isLog&&Ea(a.trendlines,c.yAxis,j,!1,this.isBar))}},point:function(a,c,d,b,g,j,e){var f,k,m,i,h,B,q,w,l,o,v,p,ia,F,E,u,t,G,x=d.data,J=g[T],a=r(c.type,this.defaultSeriesType),s=g.plotOptions[a]&&g.plotOptions[a].stacking,K=r(this.isValueAbs,
J.isValueAbs,!1);n(d.showvalues,J.showValues);var J=n(c.yAxis,0),y=this.numberFormatter;G=n(b.showshadow,1);w=n(b.compactdatamode,0);t=r(b.dataseparator,"|");f=r(d.seriesname,L);k=M(r(d.color,b.linecolor,g.colors[e%g.colors.length]));m=r(d.alpha,b.linealpha,ea);i=n(d.linethickness,b.linethickness,2);h=Boolean(n(d.dashed,b.linedashed,0));B=n(d.linedashlen,b.linedashlen,5);q=n(d.linedashgap,b.linedashgap,4);n(d.includeinlegend,1);e=n(d.showvalues,b.showvalues);l=n(d.drawanchors,d.showanchors,b.drawanchors,
b.showanchors);o=n(d.anchorsides,b.anchorsides,0);v=n(d.anchorradius,b.anchorradius,3);p=M(r(d.anchorbordercolor,b.anchorbordercolor,k));ia=n(d.anchorborderthickness,b.anchorborderthickness,1);F=M(r(d.anchorbgcolor,b.anchorbgcolor,k));E=r(d.anchoralpha,b.anchoralpha,ea);b=r(d.anchorbgalpha,b.anchorbgalpha,E);c.marker={enabled:l===void 0?m!=0:!!l,fillColor:{FCcolor:{color:F,alpha:b*E/100+L}},lineColor:{FCcolor:{color:p,alpha:E+L}},lineWidth:ia,radius:v,symbol:Wa(o)};c.name=f;c.color={FCcolor:{color:k,
alpha:m}};c.shadow={opacity:G?m/100:0};c.lineWidth=i;c.dashStyle=h?qa(B,q,i):void 0;if(n(d.includeinlegend)===0||c.name===void 0||m==0&&l!==1)c.showInLegend=!1;if(x)if(w){x=x.split(t);for(d=0;d<j;d+=1)f=y.getCleanValue(x[d]),f===null?c.data.push({y:null}):(u=!0,w=y.dataLabels(f),i=e?w:L,c.data.push({y:f,displayValue:i,toolText:w}),this.pointValueWatcher(g,f,J,s,d,0,a))}else for(d=0;d<j;d+=1)(w=x[d])?(f=y.getCleanValue(w.value,K),f===null?c.data.push({y:null}):(u=!0,n(w.anchorsides,o),n(w.anchorradius,
v),M(r(w.anchorbordercolor,p)),n(w.anchorborderthickness,ia),M(r(w.anchorbgcolor,F)),r(w.anchoralpha,E),r(w.anchorbgalpha,b),t=M(r(w.color,k)),G=r(w.alpha,m),w=S(w.tooltext,y.dataLabels(f)),i=e?w:L,c.data.push({displayValue:i,toolText:w,y:f,color:{FCcolor:{color:t,alpha:G}}}),this.pointValueWatcher(g,f,J,s,d,0,a))):c.data.push({y:null});if(!u)c.showInLegend=!1;return c},categoryAdder:function(a,c){var d,b=0,g,j=c[T],e=j.axisGridManager,f=c.xAxis,k,m=j.x,i=a.chart,h=c.chart,B=n(i.showlabels,1);h.zoomType=
"x";f.maxZoom=2;g=n(i.pixelsperpoint,15);g<=0&&(g=15);j.pixelsperpoint=g;if(a.categories&&a.categories[0]&&a.categories[0].category){if(a.categories[0].font)c.xAxis.labels.style.fontFamily=a.categories[0].font;if((g=n(a.categories[0].fontsize))!==void 0)g<1&&(g=1),c.xAxis.labels.style.fontSize=g+Oa,La(c.xAxis.labels.style);if(a.categories[0].fontcolor)c.xAxis.labels.style.color=a.categories[0].fontcolor.split(z)[0].replace(/^\#?/,"#");g=c[T].oriCatTmp;var q=a.categories[0].category;d=n(i.compactdatamode,
0);k=r(i.dataseparator,"|");if(d){e=q.split(k);for(d=0;d<e.length;d+=1)k=ja(pa(e[d],e[d].name)),g[b]=k,b+=1}else for(d=0;d<q.length;d+=1)q[d].vline?e.addVline(f,q[d],b):(k=q[d].showlabel==="0"?L:ja(pa(a.categories[0].category[d].label,a.categories[0].category[d].name)),g[b]=pa(ja(a.categories[0].category[d].tooltext),k),b+=1);if(B)f.categories=g}f=b-1||1;j.displayStartIndex=n(i.displaystartindex,0);j.displayEndIndex=n(i.displayendindex,f);if(j.displayStartIndex<0||j.displayStartIndex>=f)j.displayStartIndex=
0;if(j.displayEndIndex<=j.displayStartIndex||j.displayEndIndex>f)j.displayEndIndex=f;m.catCount=b;h.hasScroll=!0;b=h.stepZoom={};b.pixelsperpoint=j.pixelsperpoint;b.displayStartIndex=j.displayStartIndex;b.displayEndIndex=j.displayEndIndex;b.scrollColor=M(r(i.scrollcolor,Y.altHGridColor[c.chart.paletteIndex]));b.scrollHeight=n(i.scrollheight,16);b.scrollPadding=n(i.scrollpadding,c.chart.plotBorderWidth);b.scrollBtnWidth=n(i.scrollbtnwidth,i.scrollheight,16);b.scrollBtnPadding=n(i.scrollbtnpadding,
0);j.marginBottomExtraSpace+=b.scrollPadding+b.scrollHeight},postSeriesAddition:function(a,c){var d=c.chart,b=a.chart.stepZoom,g=Y.canvasBorderColor[this.paletteIndex];if(b)b.allowPinMode=n(d.allowpinmode,1),b.showToolBarButtonTooltext=n(d.showtoolbarbuttontooltext,1),b.btnResetChartTooltext=r(d.btnresetcharttooltext,"Reset Zoom"),b.btnZoomOutTooltext=r(d.btnzoomouttooltext,"Zoom out one level"),b.btnSwitchToZoomModeTooltext=r(d.btnswitchtozoommodetooltext,"Select a subset of data to zoom into it for detailed view"),
b.btnSwitchToPinModeTooltext=r(d.btnswitchtopinmodetooltext,"Switch to Pin Mode"),b.pinLineThicknessDelta=n(d.pinlinethicknessdelta,0),b.pinPaneBorderThickness=n(d.pinpaneborderthickness,1),b.pinPaneBorderColor=ca(r(d.pinpanebordercolor,g),n(d.pinpaneborderalpha,15)),b.pinPaneBgColor=ca(r(d.pinpanebgcolor,g),n(d.pinpanebgalpha,15))},placeHorizontalAxis:function(a,c,d,b,g,j,e){var f=d[T],k,m,i,h,B,q,w,l,o=0,v=0,p=10,r=1,F=0,E=0,u=!1,t=!1,G=!1;i=n(b.chart.labelstep,0);l=c.labelDisplay;var x=c.rotateLabels,
J=c.horizontalLabelPadding,s=f.marginBottomExtraSpace,K=d.chart.marginLeft;k=d.chart.marginRight;var y=f.smartLabel,z=c.slantLabels,H=g/(a.max-a.min),C=0,I=0,E={w:0,h:0};if(a.labels.style)B=a.labels.style,y.setStyle(B),m=y.getOriSize("W"),p=m.height,q=m.width+4,w=y.getOriSize("WWW").width+4;var O,A,Q=[],N=[];m=m=0;var R,P,U=c.horizontalAxisNamePadding;A=0;var c=c.staggerLines,M=C;if(a.title&&a.title.text!=L)B=a.title.style,y.setStyle(B),F=y.getOriSize("W").height,a.title.rotation=0,m=y.getSmartText(a.title.text,
g,j),v=m.height;parseInt(b.chart.chartleftmargin,10);parseInt(b.chart.chartrightmargin,10);A=g-e;switch(l){case "none":u=G=!0;x&&(o=z?300:270,m=p,p=q,q=m,u=!0);break;case "rotate":o=z?300:270;m=p;p=q;q=m;u=!0;break;case "stagger":t=u=!0;b=Math.floor((j-F)/p);b<c&&(c=b);break;default:x&&(o=z?300:270,m=p,p=q,q=m)}x=0;e=a.plotLines;for(b=e.length;x<b;x+=1)(m=e[x])&&m.label&&typeof m.label.text!==Ya&&N.push(m);e=a.plotBands;x=0;for(b=e.length;x<b;x+=1)(m=e[x])&&m.label&&typeof m.label.text!==Ya&&N.push(m);
e=a.categories||[];x=0;for(b=e.length;x<b;x+=1)Q.push({value:x,label:{text:e[x]}});x=Q.length-1;b=Q.length;t&&(c>b?c=b:c<2&&(c=2));if(b){a.scroll&&a.scroll.viewPortMin&&a.scroll.viewPortMax?(O=a.scroll.viewPortMin,m=a.scroll.viewPortMax):(O=a.min,m=a.max);R=f.width*0.08;P=(Q[0].value-O)*H;O=(m-Q[x].value)*H;f.maxLabelWidth=R;f.visibleLabelDistance=f.width*0.1;if(l==="auto"){if(R>H&&R<w)z?o=300:(o=270,f.visibleLabelDistance=f.width*0.07,f.maxLabelWidth=p),m=p,p=q,q=m,u=!0}else if(l==="rotate"){if(!z)f.visibleLabelDistance=
f.width*0.07,f.maxLabelWidth=p}else l==="stagger"&&(R*=c);w=(P+K)*2;if(l=e[0])a.labels.style&&y.setStyle(a.labels.style),l=Math.min(R,y.getOriSize(l).width+4),l>w&&(m=(l-w)/2,g-=m,A-=m,d.chart.marginLeft+=m);w=(O+k)*2;if(l=e[x])a.labels.style&&y.setStyle(a.labels.style),l=Math.min(R,y.getOriSize(h).width+4),l>w&&(m=(l-w)/2,g-=m,A-=m,d.chart.marginRight+=m);G||(i?(R*=i,R=Math.max(R,q)):(r=Math.ceil(q/R),R*=r));for(i=0;i<b;i+=1)if(m=Q[i],i%r&&m.label)m.label.text=L;else if(m&&m.label&&S(m.label.text)!==
void 0){h=m.label;if(h.style&&h.style!==B)B=h.style,y.setStyle(B);if(o&&G)k=y.getOriSize(h.text),E.w=ka(E.w,k.width+4),E.h=ka(E.h,k.height);else if(!G)k=o||t?y.getOriSize(h.text):y.getSmartText(h.text,R-4,j,u),E.w=Math.max(E.w,k.width+4),E.h=Math.max(E.h,k.height)}}i=0;for(b=N.length;i<b;i+=1)if((m=N[i])&&m.label&&S(m.label.text)!==void 0){h=m.label;if(h.style&&h.style!==B)B=h.style,y.setStyle(B);k=y.getOriSize(h.text);h.verticalAlign===Da?C=ka(C,k.height):I=ka(I,k.height)}a.scroll&&a.scroll.enabled&&
!o&&!G&&(h=E.w/2,d.chart.marginLeft<h&&(i=h-d.chart.marginLeft,A>i&&(g-=i,A-=i,d.chart.marginLeft+=i)),d.chart.marginRight<h&&(i=h-d.chart.marginRight,A>i&&(g-=i,d.chart.marginRight+=i)));if(G){if(A=p,o)A=E.w}else A=o?E.w:t?c*p:E.h;A>0&&(M+=J+A);v>0&&(M+=v+U);h=I+M+2;h>j&&(h-=j,U>h?(U-=h,h=0):(h-=U,U=0,J>h?(J-=h,h=0):(h-=J,J=0)),I>h?I-=h:(I>0&&(h-=I,I=0),h>0&&(C>h?C-=h:(C>0&&(h-=C,C=0),h>0&&((m=v-F)>h?v-=h:(h-=m,v=F,h>0&&((m=A-p)>h?A-=h:(h-=m,A=p,h>0&&(h-=v+U,v=0,h>0&&(h-=A,A=0,h>0&&(J-=h)))))))))));
J+=s;F=A+J;j=f.is3d?-d.chart.xDepth:0;b=Q.length;E=0;o?(p=R,R=A-4,a.labels.rotation=o,a.labels.align="right",a.labels.y=J-s+4,a.labels.x=q/2):t?R=R*c-4:(p=A,R-=4);for(i=0;i<b;i+=r)if((m=Q[i])&&m.label&&S(m.label.text)!==void 0){h=m.label;if(h.style&&h.style!==B)B=h.style,y.setStyle(B);if(!G)k=y.getSmartText(h.text,R,p,u),a.categories[i]=k.text;E+=1}b=N.length;for(i=o=q=0;i<b;i+=1)if((m=N[i].plotObj?N[i].plotObj:N[i])&&m.label&&S(m.label.text)!==void 0){h=m.label;if(h.style&&h.style!==B)B=h.style,
y.setStyle(B);h.verticalAlign===Da?(k=y.getSmartText(h.text,g,C,!0),o=Math.max(o,k.height),h.text=k.text,h.y=F+y.getOriSize("W").height,h.x=j):(k=y.getSmartText(h.text,g,I,!0),q=Math.max(q,k.height),h.text=k.text,h.y=-(I-y.getOriSize("W").height+J+2))}if(v>0)y.setStyle(a.title.style),m=y.getSmartText(a.title.text,g,v),a.title.text=m.text,a.title.margin=F+o+U;M=o;if(A>0)f.horizontalAxisHeight=J+A-s,M+=f.horizontalAxisHeight;v>0&&(M+=v+U);d.chart.marginBottom+=M;q>0&&(d.chart.marginTop+=q,M+=q);return M},
creditLabel:!0,defaultPlotShadow:1},l.msline);l("ssgrid",{standaloneInit:!0,defaultSeriesType:"ssgrid",chart:function(){var a=this.containerElement,c=this.dataObj,d=this.chartInstance,c=Fa({},c);c.chart=c.chart||c.graph||{};delete c.graph;var b,g,j,e=0,f,k,m=[],i=c.chart,h=c.data,B=h&&h.length,c=this.smartLabel,q=this.numberFormatter,l=a.offsetHeight,D=a.offsetWidth,o={},v=e=0,e=(i.palette>0&&i.palette<6?i.palette:n(this.paletteIndex,1))-1,a={chart:{renderTo:a,ignoreHiddenSeries:!1,events:{},spacingTop:0,
spacingRight:0,spacingBottom:0,spacingLeft:0,marginTop:0,marginRight:0,marginBottom:0,marginLeft:0,borderRadius:0,borderColor:"#000000",borderWidth:1,defaultSeriesType:"ssgrid",style:{fontFamily:r(i.basefont,"Verdana"),fontSize:Va(i.basefontsize,20)+Oa,color:r(i.basefontcolor,Y.baseFontColor[e]).replace(/^#?([a-f0-9]+)/ig,"#$1")},plotBackgroundColor:Ma},labels:{smartLabel:c},colors:["AFD8F8","F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D","A186BE","CC6600",
"FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],credits:{href:"http://www.fusioncharts.com?BS=FCHSEvalMark",text:"FusionCharts",enabled:this.creditLabel},legend:{enabled:!1},series:[],subtitle:{text:L},title:{text:L},tooltip:{enabled:!1},exporting:{buttons:{exportButton:{},printButton:{enabled:!1}}}},p=a.colors,s=a.colors.length,F=0,E=f=g=0,v=b=k=0;g=d.jsVars.cfgStore;d=a.chart;La(a.chart.style);o.showPercentValues=n(g.showpercentvalues,i.showpercentvalues,
0);o.numberItemsPerPage=r(g.numberitemsperpage,i.numberitemsperpage);o.showShadow=n(g.showshadow,i.showshadow,0);o.baseFont=r(g.basefont,i.basefont,"Verdana");j=Va(g.basefontsize,i.basefontsize,10);o.baseFontSize=j+Oa;o.baseFontColor=M(r(g.basefontcolor,i.basefontcolor,Y.baseFontColor[e]));o.alternateRowBgColor=M(r(g.alternaterowbgcolor,i.alternaterowbgcolor,Y.altHGridColor[e]));o.alternateRowBgAlpha=r(g.alternaterowbgalpha,i.alternaterowbgalpha,Y.altHGridAlpha[e])+L;o.listRowDividerThickness=n(g.listrowdividerthickness,
i.listrowdividerthickness,1);o.listRowDividerColor=M(r(g.listrowdividercolor,i.listrowdividercolor,Y.borderColor[e]));o.listRowDividerAlpha=n(g.listrowdivideralpha,i.listrowdivideralpha,Y.altHGridAlpha[e])+15+L;o.colorBoxWidth=n(g.colorboxwidth,i.colorboxwidth,8);o.colorBoxHeight=n(g.colorboxheight,i.colorboxheight,8);o.navButtonRadius=n(g.navbuttonradius,i.navbuttonradius,7);o.navButtonColor=M(r(g.navbuttoncolor,i.navbuttoncolor,Y.canvasBorderColor[e]));o.navButtonHoverColor=M(r(g.navbuttonhovercolor,
i.navbuttonhovercolor,Y.altHGridColor[e]));o.textVerticalPadding=n(g.textverticalpadding,i.textverticalpadding,3);o.navButtonPadding=n(g.navbuttonpadding,i.navbuttonpadding,5);o.colorBoxPadding=n(g.colorboxpadding,i.colorboxpadding,10);o.valueColumnPadding=n(g.valuecolumnpadding,i.valuecolumnpadding,10);o.nameColumnPadding=n(g.namecolumnpadding,i.namecolumnpadding,5);o.borderThickness=n(g.borderthickness,i.borderthickness,1);o.borderColor=M(r(g.bordercolor,i.bordercolor,Y.borderColor[e]));o.borderAlpha=
r(g.borderalpha,i.borderalpha,Y.borderAlpha[e])+L;o.bgColor=r(g.bgcolor,i.bgcolor,"FFFFFF");o.bgAlpha=r(g.bgalpha,i.bgalpha,ea);o.bgRatio=r(g.bgratio,i.bgratio,ea);o.bgAngle=r(g.bgangle,i.bgangle,ga);d.borderRadius=o.borderThickness/16;d.borderWidth=o.borderThickness;d.borderColor={FCcolor:{color:o.borderColor,alpha:o.borderAlpha}};d.backgroundColor={FCcolor:{color:o.bgColor,alpha:o.bgAlpha,ratio:o.bgRatio,angle:o.bgAngle}};j={fontFamily:o.baseFont,fontSize:o.baseFontSize,color:o.baseFontColor};La(j);
c.setStyle(j);for(e=0;e<B;e+=1)if(b=h[e],f=q.getCleanValue(b.value),k=ja(pa(b.label,b.name)),g=M(r(b.color,p[e%s])),r(b.alpha,i.plotfillalpha,ea),k!=L||f!=null)m.push({value:f,label:k,color:g}),F+=f,v+=1;for(e=0;e<v;e+=1)b=m[e],f=b.value,b.dataLabel=b.label,b.displayValue=o.showPercentValues?q.percentValue(f/F*100):q.dataLabels(f),h=c.getOriSize(b.displayValue),E=Math.max(E,h.width+o.valueColumnPadding);o.numberItemsPerPage?o.numberItemsPerPage>=v?(o.numberItemsPerPage=v,f=l/o.numberItemsPerPage,
g=v):(q=l,q-=2*(o.navButtonPadding+o.navButtonRadius),g=o.numberItemsPerPage,f=q/g):(e=parseInt(j.lineHeight,10),e+=2*o.textVerticalPadding,e=Math.max(e,o.colorBoxHeight),l/e>=v?(f=l/v,g=v):(q=l,q-=2*(o.navButtonPadding+o.navButtonRadius),g=Math.floor(q/e),f=q/g));k=D-o.colorBoxPadding-o.colorBoxWidth-o.nameColumnPadding-E-o.valueColumnPadding;b=o.colorBoxPadding+o.colorBoxWidth+o.nameColumnPadding;d.height=l;d.width=D;d.rowHeight=f;d.labelX=b;d.colorBoxWidth=o.colorBoxWidth;d.colorBoxHeight=o.colorBoxHeight;
d.colorBoxX=o.colorBoxPadding;d.valueX=o.colorBoxPadding+o.colorBoxWidth+o.nameColumnPadding+k+o.valueColumnPadding;d.valueColumnPadding=o.valueColumnPadding;d.textStyle=j;d.listRowDividerAttr={"stroke-width":o.listRowDividerThickness,stroke:{FCcolor:{color:o.listRowDividerColor,alpha:o.listRowDividerAlpha}}};d.alternateRowColor={FCcolor:{color:o.alternateRowBgColor,alpha:o.alternateRowBgAlpha}};d.navButtonRadius=o.navButtonRadius;d.navButtonPadding=o.navButtonPadding;d.navButtonColor=o.navButtonColor;
d.navButtonHoverColor=o.navButtonHoverColor;d.lineHeight=parseInt(j.lineHeight,10);l=[];o=0;q=!0;for(e=0;e<v&g!=0;e+=1)e%g==0&&(l.push({data:[],visible:q}),q=!1,o+=1),b=m[e],l[o-1].data.push({label:c.getSmartText(b.dataLabel,k,f).text,displayValue:b.displayValue,y:b.value,color:b.color});a.series=l;a.exporting.enabled=i.exportenabled=="1"?!0:!1;a.exporting.buttons.exportButton.enabled=i.exportshowmenuitem=="0"?!1:!0;a.exporting.filename=i.exportfilename?i.exportfilename:"FusionCharts";a.exporting.width=
D;return a},creditLabel:!0},l.base);Ba.stepzoom=Sa(Ba.line,{states:{hover:{}}});var rb=function(a,c,d){a<=0.01&&(a=0);var b=this.stepZoom,c=this.series,g=this.plotWidth,j=this.options._FCconf.clipExcessWidth,e=g/2,f=c.length,a=n(a,b.scrollPosition,0);a*=b.scrollablePXLength;var k,m,i,h,B,q=this.plotLeft-a;b.catGroup.attr("translateX",q);this.trackerGroup.attr("translateX",q);b.catClipRect.attr("x",a-j/2);this.clipRect&&this.clipRect.attr("x",a);for(j=0;j<f;j+=1)if(k=c[j],k.group&&k.group.attr("translateX",
q),k.dataLabelsGroup&&k.dataLabelsGroup.attr("translateX",q),k.clipRect&&k.clipRect.attr("x",a),d){b=fa.min(20,e);i=k.data;m=i.length;for(B=0;B<m;B+=1)h=i[B],h.y!==null&&h.tooltipPos&&(k=h.plotX-a,k>=0&&k<=e?k+=b:k>e&&k<=g&&(k-=b),h.tooltipPos[0]=k)}},s=P.extendClass(na.line,{type:"stepzoom",translate:function(){for(var a=this.chart,c=this.options.stacking,d=this.xAxis.categories,b=this.yAxis,g=this.data,j=g.length;j--;){var e=g[j],f=e.x,k=e.y,m=e.low,i=b.stacks[(k<0?"-":"")+this.stackKey];e.plotX=
this.xAxis.translate(f);if(c&&i&&i[f]){var f=i[f],i=f.total,h=b.options.min,m=f.cum;f.cum+=k;k=ka(h,m+k);m=ka(h,m);c==="percent"&&(m=i?m*100/i:0,k=i?k*100/i:0);e.percentage=i?e.y*100/i:0;e.stackTotal=i}if(ra(m))e.yBottom=b.translate(m,0,1,0,1);if(k!==null)e.plotY=b.translate(k,0,1,0,1);e.clientX=a.inverted?a.plotHeight-e.plotX:e.plotX;e.category=d&&d[e.x]!==Ha?d[e.x]:e.x}},drawPoints:function(){var a,c=this.data,d=this.chart,b,g,j,e,f,k,m,i;a=d.stepZoom.zoomHistory[d.stepZoom.currentZoomLevelIndex];
var h=a.perPointPixelDistance,B=a.stepping,q=a.seriesStart,l,n=this.options.marker.enabled;for(j=c.length;j--;)if(e=c[j],l=j-q,b=e.plotX=l*h,g=e.plotY,i=e.graphic,n&&g!==Ha&&!isNaN(g))a=e.pointAttr[e.selected?"select":""],m=a.r,f=b+20,k=g-15,f=f<0?0:f,k=k<0?0:k,e.tooltipPos=[f,k],i?i.animate({x:b,y:g,r:m}):e.graphic=d.renderer.symbol(za(e.marker&&e.marker.symbol,this.symbol),b,g,m).attr(a).add(this.group),(l<0||l%B!==0)&&e.graphic.hide()},drawGraph:function(){var a=this.options,c=this.chart,d=[],
b=this.group,g=a.lineColor||this.color,j=a.lineWidth,e=a.dashStyle,f=c.renderer,k=this.data,m=a.connectNullData,c=c.stepZoom.zoomHistory[c.stepZoom.currentZoomLevelIndex],i,h,B=0,q=[],l=!0,n;for(i=c.seriesStart;i<k.length;i+=c.stepping,B+=c.visiblePointDistance)h=k[i],ra(h&&h.plotY)?(n&&(d.push(I,q[0],q[1],O),n=!1),l?(n=!0,l=!1,q[0]=B,q[1]=h.plotY):d.push(B,h.plotY)):m||(l=!0,n=!1);this.graphPath=d;this.singlePoints=[];k=this.graphLine;g={stroke:g,"stroke-width":j,"stroke-linecap":"round",dashstyle:e};
k?this.graphLine.animate({d:d}):this.graphLine=f.path(d).attr(g).add(b).shadow(a.shadow,this.shadowGroup,a.shadow)},drawDataLabels:function(){if(this.options.dataLabels.enabled){var a,c,d=this.data,b=this.options.dataLabels,g=this.dataLabelsGroup,j=this.chart,e=j.renderer,f=j.options.chart,k=b.y===null,m=j.plotHeight,i,h=j.stepZoom.zoomHistory[j.stepZoom.currentZoomLevelIndex],B=h.stepping,q=h.seriesStart,l,r=this.type=="floatedcolumn",o=b.style,v=parseInt(o.fontSize,10),h=j.stepZoom,h=j.plotLeft-
h.scrollPosition*h.scrollablePXLength,p=f.valuePadding,s=f.valuePosition,F;b.rotation=f.rotateValues==1?270:void 0;if(!g)g=this.dataLabelsGroup=e.g("data-labels").attr({visibility:this.visible?oa:"hidden",zIndex:6}).translate(h,j.plotTop).add(),j.options.chart.hasScroll&&g.clip(this.clipRect);j=b.color;j==="auto"&&(j=null);o.color=za(j,this.color);ha(d,function(f,h){l=h-q;var j=f.plotX!=null?f.plotX:-999,G=za(f.plotY,-999),x=f.dataLabel,J=b.align,z=(k?f.y>=0?-6:12:b.y)-p;i=b.formatter.call(f.getLabelConfig());
if(i!=null){r&&(G=n(f.barY,G));a=j+b.x;c=G+z;switch(s){case "above":c=G+z;break;case "below":c=G-z+v;break;default:F=d[h-1],c=G+((F&&F.plotY)<f.plotY?-z+v:z)}c>m&&(c=G+z);c<v&&(c=G-z+v);if(x)x.attr({text:i}).animate({x:a,y:c});else if(ra(i))x=f.dataLabel=e.text(i,a,c).attr({align:J,rotation:b.rotation,zIndex:1}).css(o).add(g);(l<0||l%B!==0)&&x&&x.hide&&x.hide()}})}},drawTracker:function(){var a=this,c=a.chart,d=+new Date,b,g,j=c.renderer,e,f=c.stepZoom.zoomHistory[c.stepZoom.currentZoomLevelIndex],
k=f.stepping,m=f.seriesStart,i;c.options.chart.hasScroll&&c.trackerGroup.clip(a.clipRect);ha(a.data,function(f,l){if(f.y!==null){i=l-m;if(f.link!==void 0)var q={cursor:"pointer",_cursor:"hand"};b=f.pointAttr[f.selected?"select":""];g=b.r+3;f.tracker=j.circle(f.plotX,f.plotY,g).attr({fill:eb}).on(Ra?"touchstart":"mouseover",function(b){e=b.relatedTarget||b.fromElement;if(c.hoverSeries!==a&&Aa(e,"isTracker")!==d)a.onMouseOver();f.onMouseOver()}).on("mouseout",function(b){if(!a.options.stickyTracking&&
(e=b.relatedTarget||b.toElement,Aa(e,"isTracker")!==d))a.onMouseOut()}).css(q).add(c.trackerGroup);(i<0||i%k!==0)&&f.tracker&&f.tracker.hide&&f.tracker.hide()}})},render:function(){var a=this,c=a.chart,d=c.renderer,b=c.options.chart,g=c.options._FCconf,j=a.data,e;if(!c.stepZoom){var f=j.length-1,k,m=b.stepZoom,i=n(m.pixelsperpoint,30),h=n(m.displayStartIndex,0),l=n(m.displayEndIndex,f),q=c.plotWidth,w=c.plotLeft,r=m.scrollHeight,o=c.plotHeight+c.plotTop+n(m.scrollPadding,0),v,p,s;p=l-h;var j=q/p,
F,E;F=g.maxLabelWidth;E=g.visibleLabelDistance;E=j<E?Math.ceil(E/j):1;v=j<i?Math.ceil(i/j):1;j=q/(p-p%v);F=g.clipExcessWidth=F;g=h%v;k=f-f%v||1;p=(k-g)*j;s=q/p;e=p-q;p=e>0?(h-g)*j/(p-q):0;b=b.plotBorderWidth;b=d.scroller(w-b,o,q+b+b,r,!0,{size:m.scrollBtnWidth,padding:m.scrollBtnPadding},!1).attr({fill:m.scrollColor}).setScrollRatio(s).callback(function(a,b,e){rb.call(c,a,b,e)}).add(c.seriesGroup);c.stepZoom={zoomHistory:[{seriesStart:g,seriesEnd:k,stepping:v,perPointPixelDistance:j,visiblePointDistance:v*
j,seriesConf:[],scrollRatio:s,scrollPosition:p,scrollablePXLength:e}],currentZoomLevelIndex:0,pixelsPerPoint:i,displayStartIndex:h,displayEndIndex:l,scrollRatio:1,maxIndex:f,scrollPosition:p,scrollablePXLength:e,scroller:b};i=a.xAxis;f=i.categories;m=i.options.labels;h=0;i=c.stepZoom;v=o+r;r=m.align;o=m.rotation;l=m.style;h=n(parseInt(l.lineHeight),12);i.catClipRect=d.clipRect(-(F/2),0,q+F,c.chartHeight);i.catGroup=d.g("catGroup").translate(w,v).clip(i.catClipRect).add(c.seriesGroup);if(f&&f.length>
0){q=i.catLabelArr=[];F=f.length;w=m.y||0;m=m.x||0;i.catLabelClipXDisplacement=-(h/2);i.xDisplacement=m;for(h=0;h<F;h+=1)k=f[h],ra(k)&&(v=h-g,e=v*j+m,e=q[h]=d.text(k,e,w).attr({align:r,rotation:o}).css(l).add(i.catGroup),(v<0||v%E!==0)&&e.hide())}b.setScrollPosition(p)}var u,j=a.options,g=(E=(g=j.animation)&&a.animate)?g&&g.duration||500:0,t=a.clipRect;p=c.stepZoom;p=p.scrollPosition*p.scrollablePXLength;q=c.plotLeft-p;if(!t&&(w=c.plotSizeX,b=c.plotSizeY,t=a.clipRect=!c.hasRendered&&c.clipRect?c.clipRect:
d.clipRect(p,0,w,b),t.cliprectX=p,t.cliprectY=0,t.cliprectW=w,t.cliprectH=b,!c.clipRect))c.clipRect=t;if(!a.group)u=a.group=d.g("series"),u.clip(a.clipRect).attr({visibility:a.visible?oa:"hidden",zIndex:j.zIndex}).translate(q,c.plotTop).add(c.seriesGroup);E&&a.animate(!0);a.drawGraph&&a.drawGraph();a.drawPoints();a.drawDataLabels();a.options.enableMouseTracking!==!1&&a.drawTracker();E&&a.animate();setTimeout(function(){t.isAnimating=!1;if((u=a.group)&&t!==c.clipRect&&t.renderer)u.clip(a.clipRect=
c.clipRect),t.destroy()},g);a.isDirty=!1}});na.stepzoom=s;cb(P.Renderer.prototype.symbols,{_pinModeIcon:function(a,c,d,b,g){a=g.getArcPath(8,8/3,8,4/3,8,8,4,4,0,0);a=[I,8,8/3].concat(a);return a=a.concat(I,8,8,O,8,12)},zoomOutIcon:function(a,c,d,b,g){a-=1;c-=1;var j=d-0.25,b=43*V,e=48*V,d=a+j*$(b),b=c+j*X(b),f=a+j*$(e),e=c+j*X(e),k=45*V,m=d+4*$(k),i=b+4*X(k),h=f+4*$(k),k=e+4*X(k),g=g.getArcPath(a,c,d,b,f,e,j,j,0,1),j=["M",d,b],j=j.concat(g);return j=j.concat("Z","M",d+1,b+1,"L",m,i,h,k,f+1,e+1,"Z",
"M",a-2,c,"L",a+2,c,"Z")},resetIcon:function(a,c,d,b,g){a=ma&&!Z?a+0.5:a-0.25;c-=0.5;var j=ma&&!Z?d-0.2:d,b=ma&&!Z?270*V:310*V,e=ma&&!Z?180*V:225*V,d=a+j*$(b),f=c+j*X(b),b=a+j*$(e),e=c+j*X(e);X(50*V);var k=ma&&!Z?2.5:3.5,g=g.getArcPath(a,c,d,f,b+1,e,j,j,1,1),a=["M",d+1,f],a=a.concat(g);return a=ma&&!Z?a.concat("M",b,e,"L",b-k,e,b,e-k,b+k,e,b,e,"Z"):a.concat("M",b,e,"L",b+k*$(50*V),e+k*X(50*V),b+k*$(125*V),e+k*X(125*V),b,e,"Z")}});Ba.pie3d=Sa(Ba.pie,{states:{hover:{}}});var Qa=function(a,c){return fb(a[1]-
(this.pageY||this.originalEvent&&this.originalEvent.pageY)+c.top,a[0]-(this.pageX||this.originalEvent&&this.originalEvent.pageX)+c.left)};ya.prototype={parseColor:function(a,c){var d,b,g,j,e,f=c/2,k,m,i,h;this.use3DLighting?(d=sa(a,80),b=sa(a,75),g=la(a,85),j=la(a,70),e=la(a,40)):(d=sa(a,90),b=sa(a,87),g=la(a,93),j=la(a,87),e=la(a,80));k=b+z+g+z+j+z+g+z+b;i=c+z+c+z+c+z+c+z+c;m=b+z+a+z+g+z+a+z+b;h=f+z+f+z+f+z+f+z+f;return{frontOuter:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:k,
alpha:i,angle:0,ratio:"0,25,5,5,65"}},backOuter:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:b+z+a+z+e+z+a+z+b,alpha:h,angle:0,ratio:"0,62,8,8,22"}},frontInner:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:m,alpha:h,angle:0,ratio:"0,25,5,5,65"}},backInner:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:k,alpha:i,angle:0,ratio:"0,62,8,8,22"}},top:Z?{FCcolor:{gradientUnits:"objectBoundingBox",radialGradient:!0,cx:0.3,cy:0.95,r:1,
color:j+z+g+z+b,alpha:c+z+c+z+c,ratio:"0,10,90"}}:{FCcolor:{gradientUnits:"objectBoundingBox",color:j+z+j+z+g+z+b,alpha:c+z+c+z+c+z+c,angle:-72,ratio:"0,8,15,77"}},bottom:ca(a,f),startSlice:ca(d,c),endSlice:ca(d,c)}},rotate:function(a){if(!this.hasOnePoint){for(var c=this.pointElemStore,d=0,b=c.length,g;d<b;d+=1)g=c[d],g=g._confObject,g.start+=a,g.end+=a,this.updateSliceConf(g);this.refreashDrawing()}},refreashDrawing:function(){var a=function(a,d){var b=a._conf.index-d._conf.index;return b?b:a._conf.isStart-
d._conf.isStart};return function(){var c=this.slicingWallsArr,d=0,b,g=c.length,j=null,e=null,f,k=this.slicingWallsFrontGroup.element,m=this.slicingWallsBackGroup.element;for(c.sort(a);d<g;d+=1)b=c[d],f=b._conf.index,f<Ka?k.appendChild(b.element):f<ba?(k.insertBefore(b.element,j),j=b.element):f<Ua?(m.insertBefore(b.element,e),e=b.element):m.appendChild(b.element)}}(),updateSliceConf:function(a,c){var d=a.start,b=a.end,g=ta(d),j=ta(b),e,f,k,m,i,h,l,q,n,r,o,v,p,s,F,E,u=this.cx,t=this.cy,G=this.rx,x=
this.ry,J=G+2,z=x+2,K=this.innerRx,y=this.innerRy,L=this.depth,H=this.depthY,C=this.renderer,M=a.elements,P,A,Q,aa;f=$(g);k=X(g);m=$(j);i=X(j);h=u+G*f;l=t+x*k;q=u+J*f;n=t+z*k;P=l+L;A=u+G*m;Q=t+x*i;r=u+J*m;o=t+z*i;aa=Q+L;this.isDoughnut?(e=u+K*f,v=t+y*k,F=v+L,p=u+K*m,s=t+y*i,E=s+L,a.startSlice=[I,h,l,O,h,P,e,F,e,v,N],a.endSlice=[I,A,Q,O,A,aa,p,E,p,s,N]):(a.startSlice=[I,h,l,O,h,P,u,H,u,t,N],a.endSlice=[I,A,Q,O,A,aa,u,H,u,t,N]);if(Z){a&&a.clipTopPath?(a.clipTopPath[1]=q,a.clipTopPath[2]=n,a.clipTopPath[9]=
r,a.clipTopPath[10]=o):a.clipTopPath=[I,q,n,da,J,z,0,0,1,r,o,O,this.cx,this.cy,N];if(d!=b){if(g>j)if(g<ba){if(a.clipOuterFrontPath=[I,this.leftX,this.topY,O,h,this.topY,h,this.bottomY,this.leftX,this.bottomY,N,I,A,this.topY,O,this.rightX,this.topY,this.rightX,this.bottomY,A,this.bottomY,N],a.clipOuterBackPath=this.clipPathforOuter,this.isDoughnut)a.clipInnerBackPath=this.clipPathforInner,a.clipInnerFrontPath=[I,this.leftInnerX,this.topY,O,e,this.topY,e,this.bottomY,this.leftInnerX,this.bottomY,N,
I,p,this.topY,O,this.rightInnerX,this.topY,this.rightInnerX,this.bottomY,p,this.bottomY,N]}else if(j>ba){if(a.clipOuterFrontPath=this.clipPathforOuter,a.clipOuterBackPath=[I,this.rightX,this.topY,O,h,this.topY,h,this.bottomY,this.rightX,this.bottomY,N,I,A,this.topY,O,this.leftX,this.topY,this.leftX,this.bottomY,A,this.bottomY,N],this.isDoughnut)a.clipInnerBackPath=[I,this.rightInnerX,this.topY,O,e,this.topY,e,this.bottomY,this.rightInnerX,this.bottomY,N,I,p,this.topY,O,this.leftInnerX,this.topY,this.leftInnerX,
this.bottomY,p,this.bottomY,N],a.clipInnerFrontPath=this.clipPathforInner}else{if(a.clipOuterFrontPath=[I,this.rightX,this.topY,O,A,this.topY,A,this.bottomY,this.rightX,this.bottomY,N],a.clipOuterBackPath=[I,this.rightX,this.topY,O,h,this.topY,h,this.bottomY,this.rightX,this.bottomY,N],this.isDoughnut)a.clipInnerBackPath=[I,this.rightInnerX,this.topY,O,e,this.topY,e,this.bottomY,this.rightInnerX,this.bottomY,N],a.clipInnerFrontPath=[I,this.rightInnerX,this.topY,O,p,this.topY,p,this.bottomY,this.rightInnerX,
this.bottomY,N]}else if(g<ba)if(j>ba){if(a.clipOuterFrontPath=[I,h,this.topY,O,this.leftX,this.topY,this.leftX,this.bottomY,h,this.bottomY,N],a.clipOuterBackPath=[I,A,this.topY,O,this.leftX,this.topY,this.leftX,this.bottomY,A,this.bottomY,N],this.isDoughnut)a.clipInnerBackPath=[I,p,this.topY,O,this.leftInnerX,this.topY,this.leftInnerX,this.bottomY,p,this.bottomY,N],a.clipInnerFrontPath=[I,e,this.topY,O,this.leftInnerX,this.topY,this.leftInnerX,this.bottomY,e,this.bottomY,N]}else{if(a.clipOuterFrontPath=
[I,h,this.topY,O,A,this.topY,A,this.bottomY,h,this.bottomY,N],a.clipOuterBackPath=this.clipPathforNoClip,this.isDoughnut)a.clipInnerBackPath=this.clipPathforNoClip,a.clipInnerFrontPath=[I,e,this.topY,O,p,this.topY,p,this.bottomY,e,this.bottomY,N]}else if(a.clipOuterFrontPath=this.clipPathforNoClip,a.clipOuterBackPath=[I,h,this.topY,O,A,this.topY,A,this.bottomY,h,this.bottomY,N],this.isDoughnut)a.clipInnerBackPath=[I,e,this.topY,O,p,this.topY,p,this.bottomY,e,this.bottomY,N],a.clipInnerFrontPath=this.clipPathforNoClip;
e=j-g;e<0&&(e=ua-e);a.clipTopPath[7]=e>ba?1:0}else a.clipOuterFrontPath=a.clipOuterBackPath=a.clipInnerBackPath=a.clipInnerFrontPath=this.clipPathforNoClip;if(!c)a.elements.startSlice._conf.index=g,a.elements.endSlice._conf.index=j,a.clipTop.attr({d:a.clipTopPath}),a.clipOuterFront.attr({d:a.clipOuterFrontPath}),a.clipOuterBack.attr({d:a.clipOuterBackPath}),this.isDoughnut&&(a.clipInnerBack.attr({d:a.clipInnerBackPath}),a.clipInnerFront.attr({d:a.clipInnerFrontPath})),this.hasOnePoint?(a.elements.startSlice.hide(),
a.elements.endSlice.hide()):(a.elements.startSlice.attr({d:a.startSlice}).show(),a.elements.endSlice.attr({d:a.endSlice}).show())}else{f=this.moveCmdArr;k=this.lineCmdArr;m=this.closeCmdArr;var R=this.centerPoint;i=this.leftPoint;q=this.topPoint;n=this.rightPoint;r=this.bottomPoint;var T=this.leftDepthPoint,U=this.rightDepthPoint;o=this.leftInnerPoint;J=this.rightInnerPoint;z=this.leftInnerDepthPoint;L=this.rightInnerDepthPoint;if(d!=b){if(g>j?g<ba?(d=C.getArcPath(u,t,h,l,this.leftX,t,G,x,1,0),b=
C.getArcPath(u,t,this.leftX,t,this.rightX,t,G,x,1,0),Q=C.getArcPath(u,t,this.rightX,t,A,Q,G,x,1,0),a.outerBackPath=f.concat(i,b,k,U,C.getArcPath(u,H,this.rightX,H,this.leftX,H,G,x,0,0),m),a.outerFrontPath=f.concat([h,l],d,k,T,C.getArcPath(u,H,this.leftX,H,h,P,G,x,0,0),m,f,n,Q,k,[A,aa],C.getArcPath(u,H,A,aa,this.rightX,H,G,x,0,0),m),a.topBorderPath=f.concat([h,l],d,b,Q),this.isDoughnut?(h=C.getArcPath(u,t,p,s,this.rightInnerX,t,K,y,0,0),l=C.getArcPath(u,t,this.rightInnerX,t,this.leftInnerX,t,K,y,0,
0),v=C.getArcPath(u,t,this.leftInnerX,t,e,v,K,y,0,0),a.innerBackPath=f.concat(J,l,k,z,C.getArcPath(u,H,this.leftInnerX,H,this.rightInnerX,H,K,y,1,0),m),a.innerFrontPath=f.concat(o,v,k,[e,F],C.getArcPath(u,H,e,F,this.leftInnerX,H,K,y,1,0),m,f,[p,s],h,k,L,C.getArcPath(u,H,this.rightInnerX,H,p,E,K,y,1,0),m),a.topPath=a.topBorderPath.concat(k,[p,s],h,l,v,m),a.topBorderPath=a.topBorderPath.concat(f,[p,s],h,l,v)):a.topPath=a.topBorderPath.concat(k,R,m)):j>ba?(d=C.getArcPath(u,t,h,l,this.rightX,t,G,x,1,
0),b=C.getArcPath(u,t,this.rightX,t,this.leftX,t,G,x,1,0),Q=C.getArcPath(u,t,this.leftX,t,A,Q,G,x,1,0),a.outerFrontPath=f.concat(n,b,k,T,C.getArcPath(u,H,this.leftX,H,this.rightX,H,G,x,0,0),m),a.outerBackPath=f.concat([h,l],d,k,U,C.getArcPath(u,H,this.rightX,H,h,P,G,x,0,0),m,f,i,Q,k,[A,aa],C.getArcPath(u,H,A,aa,this.leftX,H,G,x,0,0),m),a.topBorderPath=f.concat([h,l],d,b,Q),this.isDoughnut?(h=C.getArcPath(u,t,p,s,this.leftInnerX,t,K,y,0,0),l=C.getArcPath(u,t,this.leftInnerX,t,this.rightInnerX,t,K,
y,0,0),v=C.getArcPath(u,t,this.rightInnerX,t,e,v,K,y,0,0),a.innerFrontPath=f.concat(o,l,k,L,C.getArcPath(u,H,this.rightInnerX,H,this.leftInnerX,H,K,y,1,0),m),a.innerBackPath=f.concat(J,v,k,[e,F],C.getArcPath(u,H,e,F,this.rightInnerX,H,K,y,1,0),m,f,[p,s],h,k,z,C.getArcPath(u,H,this.leftInnerX,H,p,E,K,y,1,0),m),a.topPath=a.topBorderPath.concat(k,[p,s],h,l,v,m),a.topBorderPath=a.topBorderPath.concat(f,[p,s],h,l,v)):a.topPath=a.topBorderPath.concat(k,R,m)):(d=C.getArcPath(u,t,h,l,this.rightX,t,G,x,1,
0),b=C.getArcPath(u,t,this.rightX,t,A,Q,G,x,1,0),a.outerFrontPath=f.concat(n,b,k,[A,aa],C.getArcPath(u,H,A,aa,this.rightX,H,G,x,0,0),m),a.outerBackPath=f.concat([h,l],d,k,U,C.getArcPath(u,H,this.rightX,H,h,P,G,x,0,0),m),a.topBorderPath=f.concat([h,l],d,b),this.isDoughnut?(h=C.getArcPath(u,t,p,s,this.rightInnerX,t,K,y,0,0),l=C.getArcPath(u,t,this.rightInnerX,t,e,v,K,y,0,0),a.innerFrontPath=f.concat([p,s],h,k,L,C.getArcPath(u,H,this.rightInnerX,H,p,E,K,y,1,0),m),a.innerBackPath=f.concat(J,l,k,[e,F],
C.getArcPath(u,H,e,F,this.rightInnerX,H,K,y,1,0),m),a.topPath=a.topBorderPath.concat(k,[p,s],h,l,m),a.topBorderPath=a.topBorderPath.concat(f,[p,s],h,l)):a.topPath=a.topBorderPath.concat(k,R,m)):g<ba?j>ba?(d=C.getArcPath(u,t,h,l,this.leftX,t,G,x,1,0),b=C.getArcPath(u,t,this.leftX,t,A,Q,G,x,1,0),a.outerBackPath=f.concat(i,b,k,[A,aa],C.getArcPath(u,H,A,aa,this.leftX,H,G,x,0,0),m),a.outerFrontPath=f.concat([h,l],d,k,T,C.getArcPath(u,H,this.leftX,H,h,P,G,x,0,0),m),a.topBorderPath=f.concat([h,l],d,b),this.isDoughnut?
(h=C.getArcPath(u,t,p,s,this.leftInnerX,t,K,y,0,0),l=C.getArcPath(u,t,this.leftInnerX,t,e,v,K,y,0,0),a.innerBackPath=f.concat([p,s],h,k,z,C.getArcPath(u,H,this.leftInnerX,H,p,E,K,y,1,0),m),a.innerFrontPath=f.concat(o,l,k,[e,F],C.getArcPath(u,H,e,F,this.leftInnerX,H,K,y,1,0),m),a.topPath=a.topBorderPath.concat(k,[p,s],h,l,m),a.topBorderPath=a.topBorderPath.concat(f,[p,s],h,l)):a.topPath=a.topBorderPath.concat(k,R,m)):(d=C.getArcPath(u,t,h,l,A,Q,G,x,1,0),a.outerBackPath=f.concat([h,l]),a.topBorderPath=
a.outerBackPath.concat(d),a.outerFrontPath=a.topBorderPath.concat(k,[A,aa],C.getArcPath(u,H,A,aa,h,P,G,x,0,0),m),this.isDoughnut?(h=C.getArcPath(u,t,p,s,e,v,K,y,0,0),a.innerBackPath=f.concat([p,s]),a.topPath=a.topBorderPath.concat(k,[p,s],h,m),a.topBorderPath=a.topBorderPath.concat(f,[p,s],h),a.innerFrontPath=a.innerBackPath.concat(h,k,[e,F],C.getArcPath(u,H,e,F,p,E,K,y,1,0),m)):a.topPath=a.topBorderPath.concat(k,R,m)):(d=C.getArcPath(u,t,h,l,A,Q,G,x,1,0),a.outerFrontPath=f.concat([h,l]),a.topBorderPath=
a.outerFrontPath.concat(d),a.outerBackPath=a.topBorderPath.concat(k,[A,aa],C.getArcPath(u,H,A,aa,h,P,G,x,0,0),m),this.isDoughnut?(h=C.getArcPath(u,t,p,s,e,v,K,y,0,0),a.innerFrontPath=f.concat([p,s]),a.topPath=a.topBorderPath.concat(k,[p,s],h,m),a.topBorderPath=a.topBorderPath.concat(a.innerFrontPath,h),a.innerBackPath=a.innerFrontPath.concat(h,k,[e,F],C.getArcPath(u,H,e,F,p,E,K,y,1,0),m)):a.topPath=a.topBorderPath.concat(k,R,m)),d=f.concat(i,k,n),h=f.concat(q,k,r),a.topPath=a.topPath.concat(d,h),
a.outerFrontPath=a.outerFrontPath.concat(d),a.outerBackPath=a.outerBackPath.concat(d),this.isDoughnut)h=f.concat(o,k,J),a.innerFrontPath=a.innerFrontPath.concat(h),a.innerBackPath=a.innerBackPath.concat(h)}else if(a.topPath=a.outerFrontPath=a.outerBackPath=[],this.isDoughnut)a.innerFrontPath=a.innerBackPath=[];if(!c)a.elements.startSlice._conf.index=g,a.elements.endSlice._conf.index=j,a.thisElement.attr({d:a.topPath}),M.topBorder.attr({d:a.topBorderPath}),M.bottom.attr({d:a.topPath}),M.bottomBorder.attr({d:a.topBorderPath}),
M.frontOuter.attr({d:a.outerFrontPath}),M.backOuter.attr({d:a.outerBackPath}),this.isDoughnut&&(M.frontInner.attr({d:a.innerFrontPath}),M.backInner.attr({d:a.innerBackPath})),this.hasOnePoint?(a.elements.startSlice.hide(),a.elements.endSlice.hide()):(a.elements.startSlice.attr({d:a.startSlice}).show(),a.elements.endSlice.attr({d:a.endSlice}).show())}},createSlice:function(){var a={stroke:!0,strokeWidth:!0,"stroke-width":!0,dashstyle:!0,"stroke-dasharray":!0,translateX:!0,translateY:!0,"stroke-opacity":!0,
fill:!0,opacity:!0,isTracker:!0,start:!0,end:!0},c=function(b,d){var c,g,i=this,h=i._confObject,j,l=h.elements,n,r,o=h.pie3DManager;typeof b==="string"&&ra(d)&&(c=b,b={},b[c]=d);if(typeof b==="string")i=a[b]?h[b]:i._attr(b);else{for(c in b)if(g=b[c],a[c])if(h[c]=g,c==="translateX"||c==="translateY"||c==="isTracker"){j={};j[c]=g;for(n in l)l[n].attr(j);i._attr(j)}else if(c==="stroke"||c==="strokeWidth"||c==="stroke-width"||c==="dashstyle"||c==="stroke-dasharray")j={},j[c]=g,l.topBorder.attr(j),l.startSlice.attr(j),
l.endSlice.attr(j),l.bottomBorder.attr(j);else{if(c!=="fill"&&(c==="start"||c==="end"))r=!0}else i._attr(c,g);r&&o.updateSliceConf(h);o.refreashDrawing()}return i},d=function(a,b){var c=this._confObject.elements,d;for(d in c)c[d].on(a,b);return this._on(a,b)},b=function(){var a=this._confObject.elements,b;for(b in a)a[b].hide();return this._hide()},g=function(){var a=this._confObject.elements,b;for(b in a)a[b].show();return this._show()},j=function(){var a=this._confObject,b=a.elements,c;for(c in b)b[c].destroy();
Z&&(a.clipTop.destroy(),a.clipOuterFront.destroy(),a.clipOuterBack.destroy(),a.clipInnerFront&&a.clipInnerFront.destroy(),a.clipInnerBack&&a.clipInnerBack.destroy());return this._destroy()};return function(a,f,k,m,i,h){var l=this.renderer,k=this.parseColor(k,m),f={start:a,end:f,elements:{},pie3DManager:this,topPath:this.topPath,topBorderPath:this.topBorderPath,outerFrontPath:this.outerFrontPath,outerBackPath:this.outerBackPath,innerFrontPath:this.innerFrontPath,innerBackPath:this.innerBackPath},m=
this.slicingWallsArr,n=f.elements;this.updateSliceConf(f,!0);a=l.path(f.topPath).attr({fill:k.top,"stroke-width":0}).add(this.topGroup);n.topBorder=l.path(f.topBorderPath).attr({stroke:i,"stroke-width":h}).add(this.topGroup);n.bottom=l.path(f.topPath).attr({fill:k.bottom,"stroke-width":0}).add(this.bottomBorderGroup);n.bottomBorder=l.path(f.topBorderPath).attr({stroke:i,"stroke-width":h}).add(this.bottomBorderGroup);n.frontOuter=l.path(f.outerFrontPath).attr({fill:k.frontOuter,"stroke-width":0}).add(this.outerFrontGroup);
n.backOuter=l.path(f.outerBackPath).attr({fill:k.backOuter,"stroke-width":0}).add(this.outerBackGroup);n.startSlice=l.path(f.startSlice).attr({fill:k.startSlice,stroke:i,"stroke-width":h}).add(this.slicingWallsFrontGroup);n.endSlice=l.path(f.endSlice).attr({fill:k.endSlice,stroke:i,"stroke-width":h}).add(this.slicingWallsFrontGroup);m.push(n.startSlice,n.endSlice);n.startSlice._conf={index:ta(f.start),isStart:1};n.endSlice._conf={index:ta(f.end),isStart:0};this.hasOnePoint&&(n.startSlice.hide(),n.endSlice.hide());
if(this.isDoughnut)n.frontInner=l.path(f.innerFrontPath).attr({fill:k.frontInner,"stroke-width":0}).add(this.innerFrontGroup),n.backInner=l.path(f.innerBackPath).attr({fill:k.backInner,"stroke-width":0}).add(this.innerBackGroup);if(Z&&(f.clipTop=l.clipPath(f.clipTopPath),f.clipOuterFront=l.clipPath(f.clipOuterFrontPath),f.clipOuterBack=l.clipPath(f.clipOuterBackPath),a.clip(f.clipTop),n.topBorder.clip(f.clipTop),n.bottom.clip(f.clipTop),n.bottomBorder.clip(f.clipTop),n.frontOuter.clip(f.clipOuterFront),
n.backOuter.clip(f.clipOuterBack),this.isDoughnut))f.clipInnerFront=l.clipPath(f.clipInnerFrontPath),f.clipInnerBack=l.clipPath(f.clipInnerBackPath),n.frontInner.clip(f.clipInnerFront),n.backInner.clip(f.clipInnerBack);a._confObject=f;f.thisElement=a;a._destroy=a.destroy;a.destroy=j;a._show=a.show;a.show=g;a._hide=a.hide;a.hide=b;a._on=a.on;a.on=d;a._attr=a.attr;a.attr=c;this.pointElemStore.push(a);return a}}()};ya.prototype.constructor=ya;P=P.extendClass(na.pie,{type:"pie3d",translate:function(){var a=
0,c=this,d=c.options,b=-1*(r(this.chart.options.chart.startingAngle,0)%360/360),g=n(d.dataLabels.distance,20),j=c.slicedOffset=d.slicedOffset,e=Fa([],d.center),f=c.chart,k=f.plotWidth,m=f.plotHeight,i,h,l,q=c.data,s=2*Ja,D,o=Ia(k,m),v,p,z,F=d.dataLabels.distance,E=c.pieYScale=d.pieYScale,u=c.pieSliceDepth=d.pieSliceDepth,t=c.managedPieSliceDepth=d.managedPieSliceDepth,G=c.slicedOffsetY=j*E;e.push(d.size,d.innerSize||0);e=Ga(e,function(a,b){return(v=/%$/.test(a))?[k,m-t,o,o][b]*parseInt(a,10)/100:
a});e[2]/=2;e[3]/=2;e.push(e[2]*E);e.push((e[2]+e[3])/2);e.push(e[5]*E);c.getX=function(a,b){l=fa.asin((a-e[1])/(e[2]+F));return e[0]+(b?-1:1)*$(l)*(e[2]+F)};c.center=e;ha(q,function(b){a+=b.y});c.labelsRadius=e[2]+g;c.labelsRadiusY=c.labelsRadius*E;c.quadrantHeight=(m-t)/2;c.quadrantWidth=k/2;var x=d.dataLabels,g=n(parseInt(x.style.fontSize,10),10)+4;c.maxLabels=Math.floor(c.quadrantHeight/g);c.labelFontSize=g;c.connectorPadding=n(x.connectorPadding,5);c.isSmartLineSlanted=r(x.isSmartLineSlanted,
!0);c.connectorWidth=n(x.connectorWidth,1);c.enableSmartLabels=x.enableSmartLabels;if(!c.pie3DManager)c.pie3DManager=new ya(e[0],e[1],e[2],e[3],E,u,void 0,f.renderer,c.data.length===1,d.use3DLighting);ha(q,function(d){D=a?d.y/a:0;i=Ca(b*s*1E3)/1E3;b+=D;h=Ca(b*s*1E3)/1E3;d.shapeArgs={start:i,end:h};d.centerAngle=l=(h+i)/2%ua;d.slicedTranslation=Ga([$(l)*j+f.plotLeft,X(l)*G+f.plotTop],Ca);p=$(l)*e[2];c.radiusY=z=X(l)*e[4];d.tooltipPos=[e[0]+p*0.7,e[1]+z];d.percentage=D*100;d.total=a});this.setTooltipPoints()},
drawDataLabels:function(){var a=function(a,b){return a.point.y-b.point.y},c=function(a,b){return a.angle-b.angle},d=["left","left","right","right"],b=[-1,1,1,-1],g=[1,1,-1,-1];return function(j){var e=this.data,f,k,l=this.chart,i=l.options.instanceAPI.smartLabel,h=this.options.dataLabels;f=h.style;var r=n(parseInt(f.lineHeight,10),12),q=h.placeInside,s=h.skipOverlapLabels,D=h.manageLabelOverflow,o=this.connectorPadding,v=this.connectorWidth,p,z=h.distance;za(h.softConnector,!0);var z=z>0,F,E=this.center,
u=E[1],t=E[0],G=E[2],x=E[4],J=[[],[],[],[]],L,K=l.plotLeft,y=l.plotTop,l=l.plotSizeX,N,H,C,M,P,A,Q,T,R,Y=this.labelsRadius;F=this.labelsRadiusY;var U,Z=this.labelFontSize,S=Z,V=S/2,o=[o,o,-o,-o],ca=this.maxLabels,ea=this.isSmartLineSlanted,ga=this.enableSmartLabels,W,da=this.pieSliceDepth/2;j||(bb.prototype.drawDataLabels.apply(this),i.setStyle(f));if(e.length==1){if(f=e[0],W=f.dataLabel,f.slicedTranslation=[K,y],W)W.attr({visibility:oa,align:"center",x:t,y:u+V-2}),W.x=t}else if(q)ha(e,function(a){if(W=
a.dataLabel){var b=a.centerAngle;R=u+E[6]*X(b)+V-2;A=t+E[5]*$(b);W.x=A;W._x=A;W.y=R;if(a.sliced){var b=a.slicedTranslation,c=b[1]-y;A+=b[0]-K;R+=c}W.attr({visibility:oa,align:"center",x:A,y:R});a.dataLabelBG=W.textBound()}});else{ha(e,function(a){if(W=a.dataLabel){var b=a.centerAngle;b<0&&(b=ua+b);J[b<Ka?1:b<ba?2:b<Ua?3:0].push({point:a,angle:b})}});for(e=j=4;e--;){if(s&&(f=J[e].length-ca,f>0)){J[e].sort(a);U=J[e].splice(0,f);q=0;for(C=U.length;q<C;q+=1)f=U[q].point,f.dataLabel.attr({visibility:"hidden"}),
f.connector&&f.connector.attr({visibility:"hidden"})}J[e].sort(c)}e=ka(J[0].length,J[1].length,J[2].length,J[3].length);U=ka(Ia(e,ca)*S,F);J[1].reverse();for(J[3].reverse();j--;){q=J[j];C=q.length;s||(S=C>ca?U/C:Z,V=S/2);f=C*S-V;F=U+V;for(e=0;e<C;e+=1,f-=S)p=Ta(U*X(q[e].angle)),F-p<S?p=F-S:p<f&&(p=f),F=q[e].oriY=p;L=d[j];C=U-C*S+V;F=-V;for(e=q.length-1;e>=0;e-=1,C+=S){f=q[e].point;k=q[e].angle;M=f.sliced;W=f.dataLabel;p=Ta(U*X(k));p-F<S?p=F+S:p>C&&(p=C);F=p;Q=(p+q[e].oriY)/2;p=t+g[j]*Y*$(fa.asin(Q/
U));Q*=b[j];Q+=u;T=u+x*X(k);P=t+G*$(k);A=p+o[j];R=Q+V-2;W.x=A;W._x=A;if(D)N=j>1?A:l-A,H=W._str=W._str||W.textStr||W.element&&W.element.innerHTML,W.attr({text:i.getSmartText(H,N,r).text});k<ba&&(Q+=da,T+=da,R+=da);W.y=R;if(M)M=f.slicedTranslation,k=M[0]-K,M=M[1]-y,A+=k,p+=k,P+=k,T+=M;W.attr({visibility:oa,align:L,x:A,y:R});f.dataLabelBG=W.textBound();if(z&&v&&ga)k=f.connector,f.connectorPath=p=[I,P,T,O,ea?p:P,Q,A,Q],k?(k.attr({d:p}),k.attr("visibility",oa)):f.connector=k=this.chart.renderer.path(p).attr({"stroke-width":v,
stroke:h.connectorColor||"#606060",visibility:oa,zIndex:3}).translate(K,y).add()}}}}}(),rotate:function(a){var c=this.data,d=this.slicedOffset,b=this.slicedOffsetY,g=this.chart.plotLeft,j=this.chart.plotTop,e=n(this.chart.options.chart.startingAngle,0),f,k=this.center;f=(a-e)%360;this.chart.options.chart.startingAngle=n(a,this.chart.options.chart.startingAngle)%360;f=f*Ja/180;this.pie3DManager&&this.pie3DManager.rotate(f);ha(c,function(a){var c=a.graphic,e=a.shapeArgs,e={start:e.start+=f,end:e.end+=
f},l=a.centerAngle=ta((e.start+e.end)/2),e=a.sliced,n=$(l),l=X(l);a.slicedTranslation=Ga([n*d+g,l*b+j],Ca);a.tooltipPos=[k[0]+n*k[2]*0.7,k[1]+l*k[4]];c&&e&&a.graphic.attr({translateX:a.slicedTranslation[0],translateY:a.slicedTranslation[1]})});this.drawDataLabels(!0)},drawPoints:function(){var a=this,c=a.chart,d,b;ha(a.data,function(g){var j=g.sliced,e=g.slicedTranslation;d=g.graphic;b=g.shapeArgs;d?d.animate(b):(g.graphic=a.pie3DManager.createSlice(b.start,b.end,g.color,g._3dAlpha,g.borderColor,
g.borderWidth),g.graphic.translate(j?e[0]:c.plotLeft,j?e[1]:c.plotTop));g.visible===!1&&g.setVisible(!1)});a.pie3DManager.refreashDrawing()},drawTracker:function(){var a=this,c=a.chart,d=+new Date,b=a.options,g,j=[a.center[0]+a.chart.plotLeft,a.center[1]+a.chart.plotTop],e,f=a.options.enableRotation,k,l,i,h,n;f&&(k=function(b){e=db(a.chart.container);a.rotationStartInstanceAngle=Qa.call(b,j,e)-a.chart.options.chart.startingAngle*V;a.chart.tooltip&&(b.type==="dragstart"?a.chart.tooltip.block(!0):(a.chart.tooltip.block(!1),
a.chart.tooltip.refresh(b.data,!0)))});ha(a.data,function(q){if(q.y!==null){if(q.link!==void 0)var r={cursor:"pointer",_cursor:"hand"};i=q.graphic;i.attr({isTracker:d});i.on(Ra?"touchstart":"mouseover",function(b){g=b.relatedTarget||b.fromElement;if(c.hoverSeries!==a&&Aa(g,"isTracker")!==d)a.onMouseOver();q.onMouseOver()}).on("mouseout",function(c){if(!b.stickyTracking&&(g=c.relatedTarget||c.toElement,Aa(g,"isTracker")!==d))a.onMouseOut()}).css(r);if(f){l=i._confObject;h=l.elements;for(n in h)va(h[n].element,
"dragstart dragend",k,q),va(h[n].element,"drag",function(b){a.rotate((Qa.call(b,j,e)-a.rotationStartInstanceAngle)/V)});va(i.element,"dragstart dragend",k,q);va(i.element,"drag",function(b){a.rotate((Qa.call(b,j,e)-a.rotationStartInstanceAngle)/V)})}}})}});na.pie3d=P}})();
